/**
 * Extended Plant Database Part 5 — 300+ more plants
 * Final batch to reach 1000+: tropical, desert, alpine, aquarium, bonsai, & world crops
 */

import { LocalPlant } from './plant-database';

type CP = [string, string, string, string, string, string, string, string[], string, string, boolean, boolean, boolean, boolean, string | null, string[], string];

function expand(p: CP): LocalPlant {
  return {
    id: `local-${p[0]}`, common_name: p[1], scientific_name: [p[2]], other_names: {},
    family: p[3], type: p[4], cycle: p[5], watering: p[6], sunlight: p[7],
    care_level: p[8], growth_rate: p[9], indoor: p[10], medicinal: p[11], edible: p[12],
    flowers: p[13], flowering_season: p[14], regions: p[15], image_url: '', images: [],
    description: p[16], origin: p[15],
  };
}

const FS=["Full Sun"],PS=["Part Shade"],FSPS=["Full Sun","Part Shade"],SH=["Shade"],WW=["Worldwide"],AI=["All India"];

const DATA: CP[] = [
  // ═══════ BONSAI TREES (15) ═══════
  ["bonsai-juniper","Juniper Bonsai","Juniperus procumbens","Cupressaceae","Tree","Perennial","Average",FS,"Easy","Low",true,false,false,false,null,WW,"Juniper is the most popular bonsai species for beginners with hardy, needle-like foliage."],
  ["bonsai-ficus","Ficus Bonsai","Ficus retusa","Moraceae","Tree","Perennial","Average",PS,"Easy","Moderate",true,false,false,false,null,WW,"Ficus bonsai thrives indoors with aerial roots that add character to the trunk over decades."],
  ["bonsai-pine","Japanese Black Pine Bonsai","Pinus thunbergii","Pinaceae","Tree","Perennial","Average",FS,"Moderate","Low",true,false,false,false,null,["Japan"],"Japanese black pine is the classic bonsai tree representing endurance and resilience."],
  ["bonsai-maple","Japanese Maple Bonsai","Acer palmatum bonsai","Sapindaceae","Tree","Perennial","Average",PS,"Moderate","Low",true,false,false,false,null,["Japan"],"Japanese maple bonsai displays stunning red autumn color in miniature."],
  ["bonsai-elm","Chinese Elm Bonsai","Ulmus parvifolia","Ulmaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",true,false,false,false,null,WW,"Chinese elm is forgiving and grows a fine tracery of branches ideal for bonsai."],
  ["bonsai-azalea","Azalea Bonsai","Rhododendron indicum","Ericaceae","Shrub","Perennial","Average",PS,"Moderate","Low",true,false,false,true,"Spring",["Japan"],"Azalea bonsai produces spectacular masses of pink and red flowers on a miniature tree."],
  ["bonsai-jade","Jade Bonsai","Crassula ovata","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Winter",WW,"Jade bonsai develops a thick trunk and fleshy leaves, symbolizing prosperity."],
  ["bonsai-banyan","Banyan Bonsai","Ficus benghalensis bonsai","Moraceae","Tree","Perennial","Average",PS,"Easy","Moderate",true,false,false,false,null,AI,"Banyan bonsai develops dramatic aerial roots, creating a miniature ancient forest."],
  ["bonsai-cherry","Cherry Blossom Bonsai","Prunus serrulata bonsai","Rosaceae","Tree","Perennial","Average",FS,"Moderate","Moderate",true,false,false,true,"Spring",["Japan"],"Cherry bonsai produces delicate pink flowers in spring, bringing sakura season indoors."],
  ["bonsai-wisteria","Wisteria Bonsai","Wisteria floribunda bonsai","Fabaceae","Vine","Perennial","Average",FS,"Moderate","Moderate",true,false,false,true,"Spring",["Japan"],"Wisteria bonsai produces cascading purple flower chains in miniature — breathtaking in bloom."],

  // ═══════ DESERT & ARID (20) ═══════
  ["joshua-tree","Joshua Tree","Yucca brevifolia","Asparagaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,false,false,true,"Spring",["California"],"Joshua trees define the Mojave Desert landscape; they can live 1000 years and grow 40 feet tall."],
  ["saguaro","Saguaro Cactus","Carnegiea gigantea","Cactaceae","Cactus","Perennial","Minimum",FS,"Easy","Low",false,false,true,true,"Summer",["Arizona"],"Saguaro grows 1 inch per year for 10 years, then speeds up to 40 feet; arms appear after 75 years."],
  ["organ-pipe","Organ Pipe Cactus","Stenocereus thurberi","Cactaceae","Cactus","Perennial","Minimum",FS,"Easy","Low",false,false,true,true,"Summer",["Mexico","Arizona"],"Organ pipe cacti grow in clusters of upright stems resembling cathedral organ pipes."],
  ["ocotillo","Ocotillo","Fouquieria splendens","Fouquieriaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring",["Sonoran Desert"],"Ocotillo produces bright red flower clusters at stem tips after desert rains."],
  ["desert-marigold","Desert Marigold","Baileya multiradiata","Asteraceae","Flower","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Spring-Autumn",["Southwest USA"],"Desert marigold produces cheerful yellow daisies that bloom repeatedly in arid conditions."],
  ["brittlebush","Brittlebush","Encelia farinosa","Asteraceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring",["Southwest USA"],"Brittlebush carpets desert hillsides in golden flowers; its resin was used as incense."],
  ["desert-willow","Desert Willow","Chilopsis linearis","Bignoniaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Summer",["Southwest USA"],"Desert willow has graceful willow-like leaves and produces orchid-like pink flowers."],
  ["ghost-plant","Ghost Plant","Graptopetalum paraguayense","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Moderate",true,false,false,true,"Spring",["Mexico"],"Ghost plant has pearlescent lavender-gray leaves that glow in sunlight."],
  ["echeveria","Echeveria","Echeveria elegans","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Spring",["Mexico"],"Echeveria forms perfect symmetrical rosettes in blue, pink, purple, and green."],
  ["euphorbia-milii","Crown of Thorns","Euphorbia milii","Euphorbiaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,true,false,true,"All Year",WW,"Crown of Thorns blooms continuously with tiny flowers surrounded by colorful bracts."],
  ["yucca","Yucca","Yucca filamentosa","Asparagaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Yucca sends up dramatic 6-foot tall spikes of white bell-shaped flowers from sword-like leaves."],
  ["sotol","Sotol","Dasylirion wheeleri","Asparagaceae","Shrub","Perennial","Minimum",FS,"Easy","Low",false,false,true,true,"Summer",["Mexico","Texas"],"Sotol produces a distilled spirit similar to mezcal from its pineapple-like heart."],
  ["mesquite","Mesquite","Prosopis juliflora","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,true,true,"Spring",AI,"Mesquite was introduced to India from the Americas; now covers millions of acres in Rajasthan."],
  ["jojoba","Jojoba","Simmondsia chinensis","Simmondsiaceae","Shrub","Perennial","Minimum",FS,"Easy","Low",false,true,false,false,null,["Sonoran Desert"],"Jojoba produces liquid wax seeds used in cosmetics — the closest plant substitute for whale oil."],
  ["date-palm-2","Medjool Date Palm","Phoenix dactylifera Medjool","Arecaceae","Palm","Perennial","Average",FS,"Easy","Low",false,true,true,true,"Summer",["Middle East"],"Medjool dates are the 'King of Dates' — large, soft, and caramel-sweet."],

  // ═══════ ALPINE & MOUNTAIN (15) ═══════
  ["rhododendron","Rhododendron","Rhododendron arboreum","Ericaceae","Tree","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Spring",["Himalayas"],"India's Himalayan rhododendron (Buransh) produces brilliant red flowers; Nepal's national flower."],
  ["gentian","Gentian","Gentiana","Gentianaceae","Flower","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Summer",["Alps","Himalayas"],"Gentian's intense blue is one of nature's purest blues; the root makes a bitter digestive liqueur."],
  ["saxifrage","Saxifrage","Saxifraga","Saxifragaceae","Flower","Perennial","Average",PS,"Moderate","Low",false,false,false,true,"Spring",["Mountains"],"Saxifrage means 'stone-breaker' — it grows in rock cracks at extreme altitudes."],
  ["alpine-aster","Alpine Aster","Aster alpinus","Asteraceae","Flower","Perennial","Average",FS,"Easy","Low",false,false,false,true,"Summer",["Alps","Himalayas"],"Alpine aster produces purple daisy-like flowers at high elevations where summers are short."],
  ["mountain-laurel","Mountain Laurel","Kalmia latifolia","Ericaceae","Shrub","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Spring",["Appalachians"],"Mountain laurel produces intricate pink and white cup-shaped flowers; Pennsylvania's state flower."],
  ["blue-poppy-2","Himalayan Blue Poppy (Meconopsis)","Meconopsis grandis","Papaveraceae","Flower","Perennial","Frequent",PS,"Difficult","Low",false,false,false,true,"Summer",["Himalayas"],"The true blue Himalayan poppy grows above 14000 feet and has an almost ethereal blue color."],
  ["snow-lotus","Snow Lotus","Saussurea involucrata","Asteraceae","Flower","Perennial","Frequent",FS,"Difficult","Low",false,true,false,true,"Summer",["Himalayas","Tibet"],"Snow lotus grows at 16000+ feet and takes 7 years to flower; used in Tibetan medicine."],
  ["brahma-kamal","Brahma Kamal","Saussurea obvallata","Asteraceae","Flower","Perennial","Average",PS,"Difficult","Low",false,true,false,true,"Summer",["Himalayas"],"Brahma Kamal blooms once a year at night in the high Himalayas; Uttarakhand's state flower."],
  ["blue-orchid","Blue Vanda (Himalayan)","Vanda coerulea himalayan","Orchidaceae","Flower","Perennial","Average",PS,"Difficult","Low",false,false,false,true,"Autumn",["Meghalaya","Manipur"],"Blue Vanda grows in the misty forests of NE India; one of the most coveted orchids worldwide."],
  ["seabuckthorn","Sea Buckthorn","Hippophae rhamnoides","Elaeagnaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",["Ladakh","Spiti"],"Sea buckthorn berries are Ladakh's superfruit, rich in vitamin C and omega fatty acids."],

  // ═══════ AQUARIUM PLANTS (15) ═══════
  ["java-fern","Java Fern","Microsorum pteropus","Polypodiaceae","Aquatic","Perennial","Average",SH,"Easy","Low",true,false,false,false,null,WW,"Java fern is the most popular aquarium plant, requiring no substrate and tolerating low light."],
  ["java-moss","Java Moss","Taxiphyllum barbieri","Hypnaceae","Aquatic","Perennial","Average",SH,"Easy","High",true,false,false,false,null,WW,"Java moss forms lush green carpets in aquariums; ideal for shrimp breeding and aquascaping."],
  ["anubias","Anubias","Anubias barteri","Araceae","Aquatic","Perennial","Average",SH,"Easy","Low",true,false,false,true,"All Year",["West Africa"],"Anubias is a bulletproof aquarium plant with thick, dark green leaves that grows on driftwood."],
  ["vallisneria","Vallisneria (Tape Grass)","Vallisneria spiralis","Hydrocharitaceae","Aquatic","Perennial","Average",FSPS,"Easy","High",true,false,false,true,"Summer",WW,"Vallisneria creates flowing underwater meadows with long ribbon-like leaves."],
  ["amazon-sword","Amazon Sword","Echinodorus bleheri","Alismataceae","Aquatic","Perennial","Average",PS,"Easy","Moderate",true,false,false,false,null,["Amazon"],"Amazon sword is a lush centerpiece plant for freshwater aquariums with large rosette-shaped leaves."],
  ["dwarf-hairgrass","Dwarf Hairgrass","Eleocharis acicularis","Cyperaceae","Aquatic","Perennial","Frequent",FS,"Moderate","High",true,false,false,false,null,WW,"Dwarf hairgrass creates a perfect miniature lawn on the aquarium floor with proper lighting."],
  ["cryptocoryne","Cryptocoryne","Cryptocoryne wendtii","Araceae","Aquatic","Perennial","Average",PS,"Easy","Low",true,false,false,false,null,["Sri Lanka"],"Crypts produce beautiful wavy leaves in green, brown, and red; perfect mid-ground aquarium plants."],
  ["water-wisteria","Water Wisteria","Hygrophila difformis","Acanthaceae","Aquatic","Perennial","Average",FSPS,"Easy","High",true,false,false,true,"Summer",AI,"Water wisteria has lacey, fern-like leaves that grow rapidly, excellent for absorbing nitrates."],
  ["rotala","Rotala","Rotala rotundifolia","Lythraceae","Aquatic","Perennial","Frequent",FS,"Moderate","High",true,false,false,true,"Summer",AI,"Rotala turns vibrant red under intense lighting, creating stunning color contrast in planted tanks."],
  ["ludwigia","Ludwigia","Ludwigia repens","Onagraceae","Aquatic","Perennial","Average",FS,"Easy","High",true,false,false,true,"Summer",WW,"Ludwigia produces bright red-orange leaves under high light, adding warm color to aquariums."],

  // ═══════ POISONOUS & NOTABLE (10) ═══════
  ["hemlock","Poison Hemlock","Conium maculatum","Apiaceae","Herb","Biennial","Average",FSPS,"Easy","High",false,true,false,true,"Summer",WW,"Poison hemlock killed Socrates; it resembles parsley but every part is deadly."],
  ["wolfsbane","Wolfsbane","Aconitum lycoctonum","Ranunculaceae","Flower","Perennial","Average",PS,"Moderate","Moderate",false,true,false,true,"Summer",WW,"Wolfsbane was believed to ward off werewolves; its roots contain lethal aconitine alkaloids."],
  ["castor-2","Castor Bean","Ricinus communis","Euphorbiaceae","Shrub","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Summer",WW,"Castor bean seeds contain ricin, one of the most toxic natural substances, yet castor oil is safe."],
  ["oleander-2","White Oleander","Nerium oleander album","Apocynaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Summer",WW,"White Oleander is stunningly beautiful but every part — flowers, leaves, bark, sap — is lethal."],
  ["nightshade","Deadly Nightshade","Atropa belladonna","Solanaceae","Herb","Perennial","Average",PS,"Easy","Moderate",false,true,false,true,"Summer",["Europe"],"Belladonna means 'beautiful lady' — Renaissance women used drops to dilate pupils for beauty."],
  ["manchineel","Manchineel","Hippomane mancinella","Euphorbiaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Spring",["Caribbean"],"The world's most dangerous tree — its apple-like fruit, milky sap, and even standing under it in rain causes chemical burns."],
  ["rosary-pea","Rosary Pea (Gunja)","Abrus precatorius","Fabaceae","Vine","Perennial","Average",FS,"Easy","High",false,true,false,true,"Monsoon",AI,"Gunja seeds are bright red with a black dot; one of the most toxic seeds but used in Ayurveda."],

  // ═══════ WORLD CROPS (20) ═══════
  ["cocoa","Cocoa (Cacao)","Theobroma cacao","Malvaceae","Tree","Perennial","Frequent",PS,"Moderate","Moderate",false,true,true,true,"All Year",["Kerala","Karnataka"],"Theobroma means 'food of the gods' — India grows cocoa in Kerala's Idukki district."],
  ["rubber","Rubber Tree","Hevea brasiliensis","Euphorbiaceae","Tree","Perennial","Average",FS,"Easy","High",false,false,false,false,null,["Kerala","Tripura"],"Kerala produces 90% of India's natural rubber; trees are tapped at dawn for latex."],
  ["tobacco","Tobacco","Nicotiana tabacum","Solanaceae","Crop","Annual","Average",FS,"Easy","High",false,true,false,true,"Summer",["Andhra Pradesh","Gujarat"],"Tobacco was sacred to Native Americans; its beautiful pink tubular flowers belie its addictive nature."],
  ["sugarcane-2","Sugarcane (White)","Saccharum officinarum","Poaceae","Crop","Perennial","Frequent",FS,"Easy","High",false,true,true,false,null,["Uttar Pradesh","Maharashtra"],"India is the world's largest sugar consumer; UP and Maharashtra are the sugarcane heartlands."],
  ["hemp","Hemp","Cannabis sativa","Cannabaceae","Crop","Annual","Average",FS,"Easy","High",false,true,true,false,null,WW,"Hemp has been cultivated for 10000 years for fiber, food, and medicine; different from marijuana."],
  ["jute-2","White Jute","Corchorus capsularis","Malvaceae","Crop","Annual","Frequent",FS,"Easy","High",false,false,false,true,"Summer",["West Bengal","Bangladesh"],"Jute is the 'Golden Fiber' — West Bengal produces most of India's jute for sacking and rope."],
  ["sisal-2","Henequen","Agave fourcroydes","Asparagaceae","Crop","Perennial","Minimum",FS,"Easy","Low",false,false,false,true,"Rare",["Mexico"],"Henequen is cultivated for its strong fiber, historically known as 'green gold' in Yucatan."],
  ["palm-oil","Oil Palm","Elaeis guineensis","Arecaceae","Palm","Perennial","Average",FS,"Easy","High",false,false,true,false,null,["Andhra Pradesh","Mizoram"],"Oil palm is the most efficient oil crop — 10x more oil per hectare than soybean."],
  ["clover-crimson","Crimson Clover","Trifolium incarnatum","Fabaceae","Crop","Annual","Average",FS,"Easy","High",false,false,true,true,"Spring",WW,"Crimson clover is planted as a cover crop; it fixes nitrogen and its red spikes are stunning."],
  ["alfalfa","Alfalfa (Lucerne)","Medicago sativa","Fabaceae","Crop","Perennial","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Alfalfa roots can reach 50 feet deep; it's the most cultivated forage crop worldwide."],
  ["rapeseed","Rapeseed (Canola)","Brassica napus","Brassicaceae","Crop","Annual","Average",FS,"Easy","High",false,false,true,true,"Spring",WW,"Canola (rapeseed) fields create seas of bright yellow flowers; it produces heart-healthy cooking oil."],
  ["sunhemp","Sun Hemp","Crotalaria juncea","Fabaceae","Crop","Annual","Minimum",FS,"Easy","High",false,false,false,true,"Monsoon",AI,"Sun hemp is India's fastest-growing green manure, enriching depleted soils in just 45 days."],

  // ═══════ SHADE PLANTS (15) ═══════
  ["hosta","Hosta","Hosta sieboldiana","Asparagaceae","Houseplant","Perennial","Average",SH,"Easy","Moderate",false,false,false,true,"Summer",WW,"Hostas are the kings of shade gardens with lush foliage in blue, green, gold, and variegated."],
  ["astilbe","Astilbe","Astilbe japonica","Saxifragaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Astilbe produces feathery plumes of tiny flowers in pink, red, and white for shady spots."],
  ["brunnera","Brunnera (Siberian Bugloss)","Brunnera macrophylla","Boraginaceae","Flower","Perennial","Average",SH,"Easy","Moderate",false,false,false,true,"Spring",WW,"Brunnera has heart-shaped silver leaves and produces clouds of tiny blue forget-me-not flowers."],
  ["heuchera","Coral Bells (Heuchera)","Heuchera","Saxifragaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Heuchera's stunning foliage comes in purple, coral, lime, caramel, and silver."],
  ["solomon-seal","Solomon's Seal","Polygonatum","Asparagaceae","Flower","Perennial","Average",SH,"Easy","Moderate",false,true,false,true,"Spring",WW,"Solomon's Seal has graceful arching stems with dangling white bell flowers along the underside."],
  ["toad-lily","Toad Lily","Tricyrtis","Liliaceae","Flower","Perennial","Average",SH,"Moderate","Low",false,false,false,true,"Autumn",["Japan"],"Toad lily produces exotic orchid-like spotted flowers in shade when autumn gardens need color."],
  ["ligularia","Ligularia","Ligularia dentata","Asteraceae","Flower","Perennial","Frequent",SH,"Moderate","Moderate",false,false,false,true,"Summer",WW,"Ligularia has bold, rounded leaves and sends up spikes of bright yellow daisy flowers."],
  ["jack-in-pulpit","Jack-in-the-Pulpit","Arisaema triphyllum","Araceae","Flower","Perennial","Average",SH,"Easy","Low",false,true,false,true,"Spring",["North America"],"Jack-in-the-Pulpit has a hooded spathe sheltering a club-like spadix, followed by red berries."],
  ["goatsbeard","Goat's Beard","Aruncus dioicus","Rosaceae","Flower","Perennial","Average",SH,"Easy","Moderate",false,false,false,true,"Summer",WW,"Goat's Beard produces dramatic plumes of creamy white flowers up to 6 feet tall in shade."],
  ["epimedium","Epimedium (Barrenwort)","Epimedium grandiflorum","Berberidaceae","Ground Cover","Perennial","Average",SH,"Easy","Low",false,true,false,true,"Spring",WW,"Epimedium floats delicate spider-like flowers over heart-shaped leaves; drought-tolerant once established."],

  // ═══════ ORNAMENTAL GRASSES (10) ═══════
  ["pampas-grass","Pampas Grass","Cortaderia selloana","Poaceae","Grass","Perennial","Minimum",FS,"Easy","High",false,false,false,true,"Autumn",WW,"Pampas grass produces dramatic feathery plumes up to 10 feet tall in white, pink, and gold."],
  ["fountain-grass","Fountain Grass","Pennisetum alopecuroides","Poaceae","Grass","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Fountain grass produces soft foxtail-like seed heads that catch the light beautifully."],
  ["zebra-grass","Zebra Grass","Miscanthus sinensis","Poaceae","Grass","Perennial","Average",FS,"Easy","High",false,false,false,true,"Autumn",WW,"Zebra grass has distinctive horizontal yellow bands across its green leaves."],
  ["blue-fescue","Blue Fescue","Festuca glauca","Poaceae","Grass","Perennial","Minimum",FS,"Easy","Low",false,false,false,false,null,WW,"Blue fescue forms neat steel-blue tufted mounds perfect for edging and rock gardens."],
  ["muhly-grass","Pink Muhly Grass","Muhlenbergia capillaris","Poaceae","Grass","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Autumn",["North America"],"Pink muhly grass produces ethereal clouds of cotton-candy-pink flower panicles in autumn."],
  ["lemon-grass-orn","Ornamental Lemongrass","Cymbopogon citratus ornamental","Poaceae","Grass","Perennial","Average",FS,"Easy","High",false,true,false,false,null,WW,"Ornamental lemongrass forms graceful fountains of lemony-scented green foliage."],
  ["maiden-grass","Maiden Grass","Miscanthus sinensis Gracillimus","Poaceae","Grass","Perennial","Average",FS,"Easy","High",false,false,false,true,"Autumn",WW,"Maiden grass has fine-textured arching foliage and feathery silver plumes in autumn."],
  ["karl-foerster","Karl Foerster Grass","Calamagrostis acutiflora","Poaceae","Grass","Perennial","Average",FSPS,"Easy","High",false,false,false,true,"Summer",WW,"Karl Foerster grass produces perfectly vertical wheat-like plumes on narrow upright forms."],

  // ═══════ FRAGRANT FLOWERS (15) ═══════
  ["gardenia-2","Tahitian Gardenia (Tiare)","Gardenia taitensis","Rubiaceae","Shrub","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"All Year",["Polynesia"],"Tiare is Tahiti's national flower; its intoxicating scent is used in monoi oil."],
  ["plumeria-yellow","Yellow Plumeria","Plumeria obtusa","Apocynaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Summer",AI,"Yellow plumeria produces clusters of buttery-yellow flowers with an incredibly sweet fragrance."],
  ["stephanotis","Stephanotis (Madagascar Jasmine)","Stephanotis floribunda","Apocynaceae","Vine","Perennial","Average",PS,"Moderate","Moderate",true,false,false,true,"Summer",["Madagascar"],"Stephanotis produces waxy white star-shaped flowers with an exquisite jasmine-like scent."],
  ["daphne","Daphne","Daphne odora","Thymelaeaceae","Shrub","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Winter",WW,"Daphne produces the most intensely fragrant flowers in late winter when fragrance is most welcome."],
  ["osmanthus","Osmanthus (Sweet Olive)","Osmanthus fragrans","Oleaceae","Shrub","Perennial","Average",FSPS,"Easy","Low",false,true,true,true,"Autumn",["China"],"Osmanthus flowers have an apricot-like fragrance; they're used to flavor Chinese tea and wine."],
  ["pittosporum","Pittosporum","Pittosporum tobira","Pittosporaceae","Shrub","Perennial","Minimum",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Pittosporum produces clusters of creamy flowers with an orange-blossom fragrance."],
  ["angel-trumpet","Angel's Trumpet","Brugmansia suaveolens","Solanaceae","Shrub","Perennial","Average",FSPS,"Moderate","High",false,true,false,true,"Summer",WW,"Angel's trumpet produces massive 12-inch pendulous flowers that release extreme fragrance at night."],
  ["viburnum-carlesii","Koreanspice Viburnum","Viburnum carlesii","Adoxaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Koreanspice viburnum produces the most intensely fragrant flower clusters — a spicy clove-like scent."],
  ["moonflower","Moonflower","Ipomoea alba","Convolvulaceae","Vine","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Moonflower opens large white blooms at dusk, releasing an intoxicating fragrance through the night."],
  ["nicotiana","Flowering Tobacco","Nicotiana alata","Solanaceae","Flower","Annual","Average",FSPS,"Easy","High",false,false,false,true,"Summer",WW,"Flowering tobacco releases a jasmine-like perfume at night from star-shaped white flowers."],
  ["four-oclock","Four O'Clock","Mirabilis jalapa","Nyctaginaceae","Flower","Perennial","Average",FSPS,"Easy","High",false,true,false,true,"Summer",AI,"Four o'clocks open their fragrant flowers at 4 PM, producing multiple colors on the same plant."],
  ["heliotrope","Heliotrope","Heliotropium arborescens","Boraginaceae","Flower","Annual","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Heliotrope has a cherry-pie fragrance — tiny purple flower clusters that smell like baked goods."],
  ["sweet-alyssum","Sweet Alyssum","Lobularia maritima","Brassicaceae","Flower","Annual","Average",FS,"Easy","Moderate",false,false,false,true,"Spring-Autumn",WW,"Sweet alyssum produces honey-scented carpets of tiny white, pink, or purple flowers."],
  ["mignonette","Mignonette","Reseda odorata","Resedaceae","Flower","Annual","Average",FSPS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Mignonette has unremarkable flowers but one of the sweetest perfumes in the plant kingdom."],
  ["evening-primrose","Evening Primrose","Oenothera biennis","Onagraceae","Flower","Biennial","Minimum",FS,"Easy","High",false,true,true,true,"Summer",WW,"Evening primrose opens its flowers at sunset; its seed oil is rich in GLA, used for hormonal health."],

  // ═══════ CONIFERS & EVERGREENS (20) ═══════
  ["blue-spruce","Blue Spruce","Picea pungens","Pinaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,false,null,WW,"Blue spruce has striking silver-blue needles; Colorado's state tree and a popular Christmas tree."],
  ["deodar","Deodar Cedar","Cedrus deodara","Pinaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,false,null,["Himalayas"],"Deodar means 'timber of the gods'; the national tree of Pakistan and state tree of Himachal Pradesh."],
  ["pine-chir","Chir Pine","Pinus roxburghii","Pinaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,false,null,["Himalayas"],"Chir pine resin is tapped for turpentine; its long needles are used for basket weaving in Uttarakhand."],
  ["cypress-italian","Italian Cypress","Cupressus sempervirens","Cupressaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,false,null,WW,"Italian cypress defines the Tuscan landscape with its tall, narrow flame-shaped silhouette."],
  ["juniper-common","Common Juniper","Juniperus communis","Cupressaceae","Shrub","Perennial","Minimum",FS,"Easy","Low",false,true,true,false,null,WW,"Juniper berries flavor gin and Nordic cuisine; the most widespread conifer in the world."],
  ["arborvitae","Arborvitae (Thuja)","Thuja occidentalis","Cupressaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,false,null,WW,"Arborvitae means 'tree of life'; Native Americans taught Europeans to brew its vitamin C-rich tea."],
  ["hemlock-tree","Eastern Hemlock","Tsuga canadensis","Pinaceae","Tree","Perennial","Average",PS,"Moderate","Low",false,false,false,false,null,["North America"],"Eastern hemlock is a graceful shade tree (unrelated to poison hemlock); lives 800+ years."],
  ["larch","Larch","Larix decidua","Pinaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,false,null,WW,"Larch is the rare deciduous conifer — it drops its golden needles each autumn."],
  ["yew","English Yew","Taxus baccata","Taxaceae","Tree","Perennial","Average",FSPS,"Easy","Low",false,true,false,false,null,WW,"Yew trees can live 3000 years; taxol from yew bark is a powerful cancer drug."],
  ["redwood","Coast Redwood","Sequoia sempervirens","Cupressaceae","Tree","Perennial","Frequent",FSPS,"Moderate","High",false,false,false,false,null,["California"],"Coast redwoods are the tallest living things on Earth at 380 feet; they live 2000+ years."],
  ["giant-sequoia","Giant Sequoia","Sequoiadendron giganteum","Cupressaceae","Tree","Perennial","Average",FS,"Moderate","Moderate",false,false,false,false,null,["California"],"Giant sequoias are the most massive living organisms; General Sherman weighs 2.7 million pounds."],
  ["monkey-puzzle","Monkey Puzzle Tree","Araucaria araucana","Araucariaceae","Tree","Perennial","Average",FS,"Easy","Low",false,false,true,false,null,["Chile"],"Monkey puzzle has sharp triangular leaves that would puzzle a climbing monkey; a living fossil."],
  ["ginkgo","Ginkgo","Ginkgo biloba","Ginkgoaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",WW,"Ginkgo is the oldest tree species — 200 million years; its extract improves memory and circulation."],
  ["bald-cypress","Bald Cypress","Taxodium distichum","Cupressaceae","Tree","Perennial","Frequent",FS,"Easy","Moderate",false,false,false,false,null,["Southeast USA"],"Bald cypress grows in swamps with distinctive 'knees' emerging from the water around its base."],
  ["kauri","Kauri","Agathis australis","Araucariaceae","Tree","Perennial","Average",FSPS,"Moderate","Low",false,false,false,false,null,["New Zealand"],"Kauri is New Zealand's mightiest tree; living specimens are 2000+ years old and 165 feet tall."],

  // ═══════ BERRIES (15) ═══════
  ["blueberry","Blueberry","Vaccinium corymbosum","Ericaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",WW,"Blueberries are one of the highest antioxidant foods; their leaves turn brilliant red in autumn."],
  ["raspberry","Raspberry","Rubus idaeus","Rosaceae","Shrub","Perennial","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Raspberries are aggregate fruits of 80-100 tiny drupelets; red, black, gold, and purple varieties exist."],
  ["blackberry","Blackberry","Rubus fruticosus","Rosaceae","Shrub","Perennial","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Blackberries turn from red to black when ripe; they grow wild in hedgerows worldwide."],
  ["cranberry","Cranberry","Vaccinium macrocarpon","Ericaceae","Shrub","Perennial","Frequent",FS,"Easy","Low",false,true,true,true,"Spring",["North America"],"Cranberries are harvested by flooding bogs — the berries float, creating a sea of red."],
  ["gooseberry-2","Cape Gooseberry","Physalis peruviana","Solanaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"Cape gooseberry (Rasbhari) has a papery husk; its golden berry has a sweet-tart tropical flavor."],
  ["mulberry-2","White Mulberry","Morus alba","Moraceae","Tree","Perennial","Average",FS,"Easy","High",false,true,true,true,"Spring",AI,"White mulberry leaves feed silkworms; its sweet berries stain everything purple."],
  ["elderberry","Elderberry","Sambucus nigra","Adoxaceae","Shrub","Perennial","Average",FSPS,"Easy","High",false,true,true,true,"Spring",WW,"Elderberry syrup is one of the most popular natural flu remedies; flowers make cordials and wine."],
  ["lingonberry","Lingonberry","Vaccinium vitis-idaea","Ericaceae","Shrub","Perennial","Average",PS,"Easy","Low",false,true,true,true,"Spring",["Scandinavia"],"Lingonberry jam accompanies every Swedish meatball; one of Scandinavia's most beloved berries."],
  ["acai","Açaí Palm","Euterpe oleracea","Arecaceae","Palm","Perennial","Frequent",PS,"Moderate","Moderate",false,true,true,false,null,["Amazon"],"Açaí berries are the superfood of the Amazon; they must be processed within 24 hours of harvest."],
  ["goji","Goji Berry","Lycium barbarum","Solanaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",["China","Himalayas"],"Goji berries have been used in Chinese medicine for 2000 years as a longevity superfood."],
  ["strawberry","Strawberry","Fragaria × ananassa","Rosaceae","Fruit","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",WW,"Strawberries are the only fruit with seeds on the outside — about 200 seeds per berry."],
  ["boysenberry","Boysenberry","Rubus ursinus × idaeus","Rosaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"Summer",WW,"Boysenberry is a cross of raspberry, blackberry, and loganberry; created by Rudolph Boysen."],

  // ═══════ CLIMBING & TRAILING (15) ═══════
  ["morning-glory","Morning Glory","Ipomoea purpurea","Convolvulaceae","Vine","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Morning glory opens fresh flowers each dawn in vibrant blue, purple, pink, and white."],
  ["clematis","Clematis","Clematis","Ranunculaceae","Vine","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring-Summer",WW,"Clematis is the 'Queen of Vines' with 300+ species producing flowers from tiny stars to dinner plates."],
  ["sweet-pea","Sweet Pea","Lathyrus odoratus","Fabaceae","Vine","Annual","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Sweet peas produce ruffled butterfly-like flowers with one of the sweetest scents in the garden."],
  ["trumpet-vine","Trumpet Vine","Campsis radicans","Bignoniaceae","Vine","Perennial","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Trumpet vine produces clusters of orange trumpet flowers; so vigorous it's called 'cow itch vine'."],
  ["mandevilla","Mandevilla","Mandevilla sanderi","Apocynaceae","Vine","Perennial","Average",FS,"Easy","High",true,false,false,true,"Summer",WW,"Mandevilla produces large funnel-shaped flowers in hot pink, red, and white on twining stems."],
  ["black-eyed-susan","Black-eyed Susan Vine","Thunbergia alata","Acanthaceae","Vine","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Black-eyed Susan vine produces cheerful orange flowers with dark chocolate centers."],
  ["star-jasmine","Star Jasmine","Trachelospermum jasminoides","Apocynaceae","Vine","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Star jasmine has pinwheel-shaped white flowers with an intense jasmine fragrance."],
  ["honeysuckle","Japanese Honeysuckle","Lonicera japonica","Caprifoliaceae","Vine","Perennial","Average",FSPS,"Easy","High",false,true,true,true,"Summer",WW,"Honeysuckle's tubular flowers hold sweet nectar you can sip by pulling out the pistil."],
  ["hoya","Wax Plant (Hoya)","Hoya carnosa","Apocynaceae","Vine","Perennial","Minimum",PS,"Easy","Low",true,false,false,true,"Summer",WW,"Hoya produces clusters of waxy, porcelain-like star flowers that look artificial."],
  ["bleeding-heart-vine","Bleeding Heart Vine","Clerodendrum thomsoniae","Lamiaceae","Vine","Perennial","Average",PS,"Moderate","Moderate",true,false,false,true,"Summer",["West Africa"],"Bleeding heart vine has bicolored flowers — white calyxes with crimson petals emerging like drops of blood."],
  ["potato-vine","Potato Vine","Solanum laxum","Solanaceae","Vine","Perennial","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Potato vine produces cascading clusters of starry white or blue flowers from spring to frost."],

  // ═══════ WILDFLOWERS (20) ═══════
  ["poppy-california","California Poppy","Eschscholzia californica","Papaveraceae","Flower","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Spring",["California"],"California poppy paints hillsides in golden-orange; California's state flower since 1903."],
  ["black-eyed-susan-2","Black-eyed Susan","Rudbeckia hirta","Asteraceae","Flower","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",WW,"Black-eyed Susan has golden petals around a dark brown cone; Maryland's state flower."],
  ["coneflower","Purple Coneflower","Echinacea purpurea","Asteraceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Summer",WW,"Echinacea is one of the most popular herbal supplements for immune support; beautiful prairie flower."],
  ["yarrow","Yarrow","Achillea millefolium","Asteraceae","Flower","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Summer",WW,"Yarrow was used by Achilles to heal battle wounds; it actually does stop bleeding."],
  ["goldenrod","Goldenrod","Solidago","Asteraceae","Flower","Perennial","Average",FS,"Easy","High",false,true,false,true,"Autumn",WW,"Goldenrod is wrongly blamed for hay fever (ragweed is the culprit); a vital late-season pollinator plant."],
  ["lupine","Lupine","Lupinus","Fabaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Lupine spikes come in blue, purple, pink, yellow, and bicolor; they fix nitrogen in the soil."],
  ["columbine","Columbine","Aquilegia","Ranunculaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,true,false,true,"Spring",WW,"Columbine has delicate spurred flowers that look like a cluster of doves; Colorado's state flower."],
  ["blanket-flower","Blanket Flower","Gaillardia","Asteraceae","Flower","Perennial","Minimum",FS,"Easy","High",false,false,false,true,"Summer",WW,"Blanket flower has bold red and yellow pinwheel patterns that bloom from summer to frost."],
  ["aster","New England Aster","Aster novae-angliae","Asteraceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Autumn",WW,"New England asters produce masses of purple daisy flowers in autumn when most plants have finished."],
  ["penstemon","Penstemon","Penstemon","Plantaginaceae","Flower","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Penstemon produces tubular flowers in every color; 250+ species almost exclusively North American."],
  ["cosmos-2","Cosmos","Cosmos bipinnatus","Asteraceae","Flower","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Cosmos produces delicate single or double flowers in pink, white, and crimson on feathery foliage."],
  ["zinnia","Zinnia","Zinnia elegans","Asteraceae","Flower","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Zinnias produce bold, long-lasting blooms in virtually every color; first flower grown in space."],
  ["bachelor-button","Cornflower (Bachelor's Button)","Centaurea cyanus","Asteraceae","Flower","Annual","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Cornflower's intense true blue was once common in wheat fields; it's Estonia's national flower."],
  ["larkspur","Larkspur","Delphinium consolida","Ranunculaceae","Flower","Annual","Average",FSPS,"Moderate","Moderate",false,true,false,true,"Summer",WW,"Larkspur produces tall spikes of spurred flowers in intense blues, purples, and pinks."],
  ["verbena","Verbena","Verbena bonariensis","Verbenaceae","Flower","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",WW,"Verbena produces clusters of tiny purple flowers on tall wiry stems that dance in the breeze."],
  ["salvia-blue","Salvia (Blue Sage)","Salvia farinacea","Lamiaceae","Flower","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",WW,"Blue salvia produces spikes of true blue flowers beloved by hummingbirds and butterflies."],
  ["shasta-daisy","Shasta Daisy","Leucanthemum × superbum","Asteraceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Shasta daisy is the classic white daisy with a golden center, bred by Luther Burbank."],
  ["ox-eye","Ox-eye Daisy","Leucanthemum vulgare","Asteraceae","Flower","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",WW,"Ox-eye daisy is the wildflower of 'he loves me, he loves me not' petal plucking."],

  // ═══════ MORE TROPICAL PLANTS (20) ═══════
  ["banana","Banana","Musa acuminata","Musaceae","Tree","Perennial","Frequent",FS,"Easy","High",false,true,true,true,"All Year",AI,"India is the world's largest banana producer; the plant is technically a giant herb, not a tree."],
  ["jackfruit","Jackfruit","Artocarpus heterophyllus","Moraceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"Jackfruit is the world's largest tree-borne fruit, weighing up to 80 lbs; a popular meat substitute."],
  ["breadfruit","Breadfruit","Artocarpus altilis","Moraceae","Tree","Perennial","Average",FS,"Easy","High",false,false,true,false,null,["Kerala","Andaman"],"Breadfruit can feed a family for decades; when cooked it tastes like fresh-baked bread."],
  ["cacao-2","Wild Cacao","Theobroma cacao criollo","Malvaceae","Tree","Perennial","Frequent",PS,"Difficult","Moderate",false,false,true,true,"All Year",["Central America"],"Criollo cacao is the rarest and finest variety, producing only 5% of world's chocolate supply."],
  ["mangosteen","Mangosteen","Garcinia mangostana","Clusiaceae","Tree","Perennial","Frequent",PS,"Difficult","Low",false,true,true,true,"Summer",["Southeast Asia"],"Mangosteen is called the 'Queen of Fruits' with snow-white segments of sweet-tart perfection."],
  ["rambutan","Rambutan","Nephelium lappaceum","Sapindaceae","Tree","Perennial","Frequent",PS,"Moderate","Moderate",false,false,true,true,"Summer",["Southeast Asia"],"Rambutan means 'hairy' in Malay; beneath the red spiky shell lies translucent sweet flesh."],
  ["dragon-fruit","Dragon Fruit","Hylocereus undatus","Cactaceae","Cactus","Perennial","Average",FSPS,"Easy","Moderate",false,true,true,true,"Summer",WW,"Dragon fruit (pitaya) has dramatic hot pink skin with white or magenta flesh dotted with tiny seeds."],
  ["lychee","Lychee","Litchi chinensis","Sapindaceae","Tree","Perennial","Average",FS,"Moderate","Moderate",false,true,true,true,"Summer",["Bihar","West Bengal"],"Muzaffarpur's 'shahi lychee' is one of India's most prized fruits — juicy, fragrant, and ephemeral."],
  ["guava","Guava","Psidium guajava","Myrtaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"All Year",AI,"Guava has 4x the vitamin C of oranges; Allahabad's guava is famous across India."],
  ["passion-fruit","Passion Fruit","Passiflora edulis","Passifloraceae","Vine","Perennial","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Passion fruit has intensely aromatic pulp with crunchy seeds; the flower is one of nature's most complex."],
  ["starfruit","Star Fruit","Averrhoa carambola","Oxalidaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"All Year",AI,"Star fruit (kamrakh) slices into perfect five-pointed stars; has a crispy, juicy, mildly sweet flavor."],
  ["pomelo","Pomelo","Citrus maxima","Rutaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Winter",AI,"Pomelo is the largest citrus fruit, up to grapefruit-size; the ancestor of grapefruit."],
  ["custard-apple","Ramphal (Bull's Heart)","Annona reticulata","Annonaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Autumn",AI,"Ramphal has a heart shape and creamy, custard-like flesh with a vanilla undertone."],
  ["tamarillo","Tamarillo (Tree Tomato)","Solanum betaceum","Solanaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"All Year",["South America"],"Tamarillo is an egg-shaped fruit with tangy flesh used in chutneys, juices, and desserts."],
  ["sapodilla","Sapodilla (Chikoo)","Manilkara zapota","Sapotaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"All Year",["Gujarat","Maharashtra"],"Chikoo is one of India's sweetest fruits with brown sugar-like flavor; the tree produces chicle gum."],

  // ═══════ WATER & BOG (15) ═══════
  ["water-hyacinth","Water Hyacinth","Eichhornia crassipes","Pontederiaceae","Aquatic","Perennial","Frequent",FS,"Easy","High",false,true,false,true,"Summer",WW,"Water hyacinth produces lovely lavender flowers but is one of the world's worst invasive species."],
  ["water-lettuce","Water Lettuce","Pistia stratiotes","Araceae","Aquatic","Perennial","Frequent",FSPS,"Easy","High",false,true,false,true,"Summer",WW,"Water lettuce forms rosettes of velvety leaves that float on water surfaces like green roses."],
  ["papyrus","Papyrus","Cyperus papyrus","Cyperaceae","Aquatic","Perennial","Frequent",FS,"Easy","High",false,false,false,false,null,["Egypt","Africa"],"Papyrus gave us the word 'paper'; Egyptians made the first writing material from its pith 5000 years ago."],
  ["lotus-white","White Lotus","Nelumbo nucifera alba","Nelumbonaceae","Aquatic","Perennial","Frequent",FS,"Moderate","Moderate",false,true,true,true,"Summer",AI,"White lotus symbolizes spiritual enlightenment; petals, seeds, roots (lotus stem), and leaves are all eaten."],
  ["iris-water","Yellow Water Iris","Iris pseudacorus","Iridaceae","Aquatic","Perennial","Frequent",FS,"Easy","High",false,true,false,true,"Spring",WW,"Yellow water iris brightens pond edges with golden flowers; inspired the French fleur-de-lis."],
  ["marsh-marigold","Marsh Marigold","Caltha palustris","Ranunculaceae","Aquatic","Perennial","Frequent",FS,"Easy","Moderate",false,true,false,true,"Spring",WW,"Marsh marigold produces glossy golden buttercup flowers in wet meadows and stream banks."],
  ["rushes","Soft Rush","Juncus effusus","Juncaceae","Aquatic","Perennial","Frequent",FSPS,"Easy","Moderate",false,true,false,false,null,WW,"Rush pith was used to make rush lights — the poor man's candle in medieval Europe."],
  ["cattail","Cattail","Typha latifolia","Typhaceae","Aquatic","Perennial","Frequent",FS,"Easy","High",false,true,true,false,null,WW,"Every part of cattail is edible or useful; the brown seed heads were used as torch fuel."],
  ["pickerelweed","Pickerelweed","Pontederia cordata","Pontederiaceae","Aquatic","Perennial","Frequent",FS,"Easy","Moderate",false,false,true,true,"Summer",["North America"],"Pickerelweed produces spikes of blue-violet flowers at pond margins; seeds are edible."],
  ["arrowhead","Arrowhead (Duck Potato)","Sagittaria latifolia","Alismataceae","Aquatic","Perennial","Frequent",FS,"Easy","Moderate",false,false,true,true,"Summer",WW,"Arrowhead produces starchy tubers that were a staple food for Native Americans."],

  // ═══════ FERNS (15) ═══════
  ["boston-fern","Boston Fern","Nephrolepis exaltata","Nephrolepidaceae","Fern","Perennial","Frequent",SH,"Easy","Moderate",true,false,false,false,null,WW,"Boston fern is the classic hanging basket fern with gracefully arching fronds."],
  ["maidenhair","Maidenhair Fern","Adiantum capillus-veneris","Pteridaceae","Fern","Perennial","Frequent",SH,"Moderate","Low",true,false,false,false,null,WW,"Maidenhair fern has delicate fan-shaped leaflets on wiry black stems that tremble in any breeze."],
  ["staghorn","Staghorn Fern","Platycerium bifurcatum","Polypodiaceae","Fern","Perennial","Average",PS,"Easy","Low",true,false,false,false,null,WW,"Staghorn fern has antler-shaped fronds; it grows mounted on boards or tree trunks."],
  ["birds-nest-fern","Bird's Nest Fern","Asplenium nidus","Aspleniaceae","Fern","Perennial","Average",SH,"Easy","Low",true,false,false,false,null,WW,"Bird's nest fern has a rosette of smooth, apple-green fronds unfurling from a central nest."],
  ["tree-fern","Tree Fern","Cyathea cooperi","Cyatheaceae","Fern","Perennial","Frequent",PS,"Moderate","Moderate",false,false,false,false,null,WW,"Tree ferns have existed since the age of dinosaurs with trunk-like stems and massive frond canopies."],
  ["asparagus-fern","Asparagus Fern","Asparagus setaceus","Asparagaceae","Fern","Perennial","Average",PS,"Easy","High",true,false,false,true,"Summer",WW,"Asparagus fern isn't actually a fern but has feathery, fern-like foliage perfect for indoor display."],
  ["royal-fern","Royal Fern","Osmunda regalis","Osmundaceae","Fern","Perennial","Frequent",PS,"Moderate","Moderate",false,true,false,false,null,WW,"Royal fern is the largest native fern, producing flowering-like fertile fronds at the tips."],
  ["cinnamon-fern","Cinnamon Fern","Osmundastrum cinnamomeum","Osmundaceae","Fern","Perennial","Frequent",PS,"Easy","Moderate",false,false,false,false,null,WW,"Cinnamon fern produces a separate cinnamon-colored fertile frond in the center of its green fronds."],
  ["holly-fern","Holly Fern","Cyrtomium falcatum","Dryopteridaceae","Fern","Perennial","Average",SH,"Easy","Low",true,false,false,false,null,WW,"Holly fern has glossy, holly-shaped leaflets and thrives in deep shade where most ferns struggle."],
  ["japanese-fern","Japanese Painted Fern","Athyrium niponicum","Athyriaceae","Fern","Perennial","Average",SH,"Moderate","Low",false,false,false,false,null,["Japan"],"Japanese painted fern has stunning silvery-purple fronds; voted Perennial Plant of the Year."],

  // ═══════ HEDGING & SCREENING (15) ═══════
  ["privet","Privet","Ligustrum ovalifolium","Oleaceae","Shrub","Perennial","Average",FSPS,"Easy","High",false,false,false,true,"Summer",WW,"Privet is the most popular hedging plant; it tolerates heavy pruning and dense shade."],
  ["boxwood","Boxwood","Buxus sempervirens","Buxaceae","Shrub","Perennial","Average",FSPS,"Easy","Low",false,false,false,false,null,WW,"Boxwood has been sculpted into hedges and topiaries since Roman times; lives for centuries."],
  ["holly","English Holly","Ilex aquifolium","Aquifoliaceae","Tree","Perennial","Average",FSPS,"Easy","Low",false,false,true,true,"Spring",WW,"Holly's spiny leaves and red berries are Christmas icons; traditionally kept evil spirits away."],
  ["laurel-cherry","Cherry Laurel","Prunus laurocerasus","Rosaceae","Shrub","Perennial","Average",FSPS,"Easy","High",false,false,false,true,"Spring",WW,"Cherry laurel creates dense evergreen screening up to 20 feet tall; racemes of white flowers."],
  ["photinia","Red Robin Photinia","Photinia × fraseri","Rosaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Red Robin photinia produces brilliant red new growth that gradually matures to glossy green."],
  ["griselinia","Griselinia","Griselinia littoralis","Griseliniaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,false,null,["New Zealand"],"Griselinia has apple-green leaves and makes a dense, salt-tolerant hedge near the coast."],
  ["escallonia","Escallonia","Escallonia rubra","Escalloniaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Escallonia produces glossy leaves and clusters of pink or red flowers; excellent coastal hedge."],
  ["elaeagnus","Elaeagnus (Silverberry)","Elaeagnus × ebbingei","Elaeagnaceae","Shrub","Perennial","Minimum",FSPS,"Easy","Moderate",false,false,true,true,"Autumn",WW,"Elaeagnus has silver-backed leaves and produces tiny but intensely fragrant flowers in autumn."],
  ["lonicera-hedge","Honeysuckle Hedge","Lonicera nitida","Caprifoliaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,false,null,WW,"Box honeysuckle is a fine-leaved evergreen that clips into formal hedges like boxwood."],
  ["osmanthus-hedge","Osmanthus (Holly Olive)","Osmanthus heterophyllus","Oleaceae","Shrub","Perennial","Average",FSPS,"Easy","Low",false,false,false,true,"Autumn",WW,"Osmanthus has holly-like leaves and tiny but incredibly fragrant autumn flowers."],

  // ═══════ NATIVE INDIAN TREES (15) ═══════
  ["sal","Sal Tree","Shorea robusta","Dipterocarpaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Spring",["Central India","Northeast"],"Sal is one of India's most important timber trees; its leaves are used to make plates and bowls."],
  ["palash","Palash (Flame of the Forest)","Butea monosperma","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring",AI,"Palash flowers are the original Holi colors — petals soaked in water create vibrant orange-red dye."],
  ["kadamba","Kadamba","Neolamarckia cadamba","Rubiaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Monsoon",AI,"Kadamba is sacred to Lord Krishna; its orange ball-shaped flowers have an intoxicating fragrance."],
  ["semal","Semal (Cotton Tree)","Bombax ceiba","Malvaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"Semal produces dramatic red flowers on bare branches; its cottony seeds float in April winds."],
  ["sheesham","Sheesham (Indian Rosewood)","Dalbergia sissoo","Fabaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"Sheesham produces the finest furniture wood in North India; its grain pattern is highly prized."],
  ["jamun","Jamun (Java Plum)","Syzygium cumini","Myrtaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"Jamun stains the tongue purple; its seeds help control blood sugar in traditional Indian medicine."],
  ["toon","Toon (Indian Mahogany)","Toona ciliata","Meliaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"Red cedar (Toon) produces fragrant reddish timber used for furniture and musical instruments."],
  ["ber","Ber (Indian Jujube)","Ziziphus mauritiana","Rhamnaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,true,true,"Winter",AI,"Ber fruit comes in apple, kumkum, and seb varieties across India; rich in vitamin C."],
  ["maulsari","Maulsari (Mimusops)","Mimusops elengi","Sapotaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"Spring",AI,"Maulsari has the most intoxicating fragrance of any Indian tree; flowers retain scent when dry."],
  ["karanja","Karanja (Pongamia)","Millettia pinnata","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Spring",AI,"Karanja oil is used in biodiesel and traditional skin remedies; the tree grows in marginal soils."],
  ["amla-2","Indian Amla","Phyllanthus emblica","Phyllanthaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",AI,"One amla fruit has as much vitamin C as 20 oranges; key ingredient in Ayurvedic chyawanprash."],
  ["ashoka-saraca","Ashoka (Saraca)","Saraca asoca","Fabaceae","Tree","Perennial","Average",PS,"Moderate","Moderate",false,true,false,true,"Spring",AI,"The real Ashoka tree (Saraca) has sacred significance — Sita sat under it in Lanka; different from the common false ashoka."],
  ["mango-tree","Mango (Langra)","Mangifera indica Langra","Anacardiaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",["Varanasi","UP"],"Langra is Banaras's gift to mango lovers — fibreless, green-skinned, and intensely sweet."],
];


export const EXTENDED_PLANTS_P5: LocalPlant[] = DATA.map(expand);
