/**
 * Extended Plant Database Part 6 — 350+ final plants
 * Bringing total local database past 1000 entries
 */

import { LocalPlant } from './plant-database';

type CP = [string, string, string, string, string, string, string, string[], string, string, boolean, boolean, boolean, boolean, string | null, string[], string];

function expand(p: CP): LocalPlant {
  return {
    id: `local-${p[0]}`, common_name: p[1], scientific_name: [p[2]], other_names: {},
    family: p[3], type: p[4], cycle: p[5], watering: p[6], sunlight: p[7],
    care_level: p[8], growth_rate: p[9], indoor: p[10], medicinal: p[11], edible: p[12],
    flowers: p[13], flowering_season: p[14], regions: p[15], image_url: '', images: [],
    description: p[16], origin: p[15],
  };
}

const FS=["Full Sun"],PS=["Part Shade"],FSPS=["Full Sun","Part Shade"],SH=["Shade"],WW=["Worldwide"],AI=["All India"];

const DATA: CP[] = [
  // ═══════ MORE ORCHID SPECIES (10) ═══════
  ["epidendrum","Epidendrum Orchid","Epidendrum ibaguense","Orchidaceae","Flower","Perennial","Average",PS,"Easy","Moderate",true,false,false,true,"All Year",WW,"Reed-stem epidendrum produces clusters of tiny flowers continuously, one of the easiest orchids."],
  ["miltonia","Pansy Orchid","Miltonia","Orchidaceae","Flower","Perennial","Average",PS,"Moderate","Moderate",true,false,false,true,"Spring",WW,"Pansy orchids have large flat flowers resembling garden pansies with distinctive waterfall patterns."],
  ["zygopetalum","Zygopetalum Orchid","Zygopetalum mackayi","Orchidaceae","Flower","Perennial","Average",PS,"Moderate","Low",true,false,false,true,"Autumn",["South America"],"Zygopetalum has intensely fragrant blooms with stunning purple patterns on green petals."],
  ["brassavola","Lady of the Night Orchid","Brassavola nodosa","Orchidaceae","Flower","Perennial","Minimum",PS,"Easy","Moderate",true,false,false,true,"All Year",["Central America"],"Lady of the Night releases an incredible citrus fragrance only after dark."],
  ["coelogyne","Coelogyne Orchid","Coelogyne cristata","Orchidaceae","Flower","Perennial","Average",PS,"Moderate","Low",true,false,false,true,"Winter",["Himalayas"],"Coelogyne produces cascading chains of pristine white flowers with golden centers in winter."],
  ["paphiopedilum","Slipper Orchid","Paphiopedilum insigne","Orchidaceae","Flower","Perennial","Average",SH,"Moderate","Low",true,false,false,true,"Winter",["Northeast India"],"Slipper orchids have pouch-shaped lips that trap pollinating insects."],
  ["cymbidium","Cymbidium Orchid","Cymbidium","Orchidaceae","Flower","Perennial","Average",PS,"Moderate","Moderate",true,false,false,true,"Winter",["Himalayas"],"Cymbidiums produce long-lasting sprays of waxy flowers; prized for Chinese New Year arrangements."],
  ["maxillaria","Coconut Orchid","Maxillaria tenuifolia","Orchidaceae","Flower","Perennial","Minimum",PS,"Easy","Moderate",true,false,false,true,"Spring",["Central America"],"Coconut orchid produces small red flowers with an unmistakable coconut fragrance."],
  ["ludisia","Jewel Orchid","Ludisia discolor","Orchidaceae","Houseplant","Perennial","Average",SH,"Easy","Low",true,false,false,true,"Winter",["Southeast Asia"],"Jewel orchids are grown for their velvety leaves with gold or silver pinstripe patterns."],
  ["bulbophyllum","Bulbophyllum Orchid","Bulbophyllum","Orchidaceae","Flower","Perennial","Frequent",SH,"Difficult","Low",true,false,false,true,"Summer",WW,"Bulbophyllum is the largest orchid genus with 2000+ species, some with bizarre moving lips."],

  // ═══════ SUCCULENTS & CACTI (20) ═══════
  ["burro-tail","Burro's Tail","Sedum morganianum","Crassulaceae","Succulent","Perennial","Minimum",PS,"Easy","Moderate",true,false,false,true,"Summer",["Mexico"],"Burro's Tail has cascading stems of plump teardrop-shaped leaves perfect for hanging baskets."],
  ["string-pearls","String of Pearls","Senecio rowleyanus","Asteraceae","Succulent","Perennial","Minimum",PS,"Easy","High",true,false,false,true,"Summer",["South Africa"],"String of Pearls has round pea-shaped leaves trailing on thread-like stems."],
  ["string-bananas","String of Bananas","Senecio radicans","Asteraceae","Succulent","Perennial","Minimum",PS,"Easy","High",true,false,false,true,"Summer",["South Africa"],"String of Bananas has curved banana-shaped leaves; easier to grow than String of Pearls."],
  ["bear-paw","Bear Paw Succulent","Cotyledon tomentosa","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Spring",["South Africa"],"Bear Paw has fuzzy leaves with tooth-shaped edges resembling tiny bear paws."],
  ["pencil-cactus","Pencil Cactus","Euphorbia tirucalli","Euphorbiaceae","Succulent","Perennial","Minimum",FS,"Easy","High",true,false,false,false,null,WW,"Pencil cactus is actually a euphorbia with cylindrical green stems that turn orange-red in sun."],
  ["moon-cactus","Moon Cactus","Gymnocalycium mihanovichii","Cactaceae","Cactus","Perennial","Minimum",PS,"Easy","Low",true,false,false,true,"Spring",WW,"Moon cactus is a colorful mutant grafted onto a green rootstock, producing no chlorophyll of its own."],
  ["bunny-ears","Bunny Ears Cactus","Opuntia microdasys","Cactaceae","Cactus","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Summer",["Mexico"],"Bunny ears cactus has cute pad-shaped segments but tiny barbed glochids that embed in skin."],
  ["fairy-castle","Fairy Castle Cactus","Acanthocereus tetragonus","Cactaceae","Cactus","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Summer",WW,"Fairy castle cactus has numerous columnar stems of different heights resembling a castle."],
  ["old-man-cactus","Old Man Cactus","Cephalocereus senilis","Cactaceae","Cactus","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Spring",["Mexico"],"Old man cactus is covered in long white hair-like spines that protect it from desert sun."],
  ["san-pedro","San Pedro Cactus","Echinopsis pachanoi","Cactaceae","Cactus","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",["Peru"],"San Pedro is a fast-growing columnar cactus with medicinal history spanning 3000 years."],
  ["aeonium","Aeonium","Aeonium arboreum","Crassulaceae","Succulent","Perennial","Minimum",FSPS,"Easy","Moderate",true,false,false,true,"Winter",["Canary Islands"],"Aeonium forms rosettes on branch tips; the black variety 'Zwartkop' is particularly dramatic."],
  ["graptoveria","Graptoveria","× Graptoveria","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Spring",WW,"Graptoveria hybrids form chunky colorful rosettes in pastel lavender, peach, and sage."],
  ["crassula","Jade Tree","Crassula arborescens","Crassulaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",true,false,false,true,"Winter",["South Africa"],"Silver jade has round blue-gray leaves edged in red, developing a tree-like form over time."],
  ["senecio-blue","Blue Chalk Sticks","Senecio serpens","Asteraceae","Succulent","Perennial","Minimum",FS,"Easy","Moderate",true,false,false,false,null,["South Africa"],"Blue chalk sticks forms clumps of powdery blue cylindrical leaves, excellent as ground cover."],
  ["euphorbia-obesa","Baseball Plant","Euphorbia obesa","Euphorbiaceae","Succulent","Perennial","Minimum",FS,"Moderate","Low",true,false,false,false,null,["South Africa"],"Baseball plant is a nearly perfect sphere with subtle striping — an endangered collector's plant."],

  // ═══════ JAPANESE GARDEN (15) ═══════
  ["japanese-iris","Japanese Iris","Iris ensata","Iridaceae","Flower","Perennial","Frequent",FSPS,"Moderate","Moderate",false,false,false,true,"Summer",["Japan"],"Japanese iris produces the largest and most elaborate iris flowers in purple, white, and pink."],
  ["japanese-quince","Japanese Quince","Chaenomeles japonica","Rosaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"Spring",["Japan"],"Japanese quince produces red or pink flowers on bare branches before leaves in early spring."],
  ["japanese-snowbell","Japanese Snowbell","Styrax japonicus","Styracaceae","Tree","Perennial","Average",PS,"Moderate","Moderate",false,false,false,true,"Spring",["Japan"],"Japanese snowbell produces elegant pendant white bell-shaped flowers along horizontal branches."],
  ["japanese-anemone","Japanese Anemone","Anemone hupehensis","Ranunculaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Autumn",["Japan","China"],"Japanese anemone produces elegant pink or white flowers on tall wiry stems in autumn."],
  ["nandina","Heavenly Bamboo","Nandina domestica","Berberidaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"Summer",["Japan"],"Heavenly bamboo has lacy foliage turning from green to red, with persistent red berries."],
  ["japanese-hydrangea","Lacecap Hydrangea","Hydrangea macrophylla normalis","Hydrangeaceae","Shrub","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Summer",["Japan"],"Lacecap hydrangeas have flat flower heads with tiny fertile flowers ringed by larger sterile ones."],
  ["camellia-sasanqua","Sasanqua Camellia","Camellia sasanqua","Theaceae","Shrub","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Autumn",["Japan"],"Sasanqua camellias bloom in autumn with a sweet fragrance and delicate petals that fall gracefully."],
  ["ophiopogon","Black Mondo Grass","Ophiopogon planiscapus Nigrescens","Asparagaceae","Grass","Perennial","Average",PS,"Easy","Low",false,false,false,true,"Summer",["Japan"],"Black mondo grass has near-black strap-shaped leaves — one of the darkest plants in nature."],
  ["hakone-grass","Hakone Grass","Hakonechloa macra","Poaceae","Grass","Perennial","Average",SH,"Easy","Low",false,false,false,false,null,["Japan"],"Hakone grass cascades gracefully in golden-green waves; the finest ornamental grass for shade."],
  ["japanese-painted","Japanese Painted Fern (Regal)","Athyrium niponicum Regal Red","Athyriaceae","Fern","Perennial","Average",SH,"Moderate","Low",false,false,false,false,null,["Japan"],"Regal Red painted fern has the most intense burgundy-silver coloration of any fern."],

  // ═══════ SOUTH AMERICAN (15) ═══════
  ["yerba-mate","Yerba Mate","Ilex paraguariensis","Aquifoliaceae","Tree","Perennial","Average",PS,"Moderate","Moderate",false,true,true,true,"Spring",["South America"],"Yerba mate is South America's coffee — a caffeinated tea drunk from gourds with metal straws."],
  ["angel-wing-begonia","Angel Wing Begonia","Begonia coccinea","Begoniaceae","Houseplant","Perennial","Average",PS,"Easy","Moderate",true,false,false,true,"All Year",["Brazil"],"Angel wing begonias have wing-shaped spotted leaves and dangling clusters of red flowers."],
  ["calathea","Calathea (Rattlesnake)","Calathea lancifolia","Marantaceae","Houseplant","Perennial","Average",SH,"Moderate","Moderate",true,false,false,false,null,["Brazil"],"Calathea has wavy leaves with spotted patterns — the undersides are deep purple."],
  ["stromanthe","Stromanthe (Triostar)","Stromanthe sanguinea","Marantaceae","Houseplant","Perennial","Average",SH,"Moderate","Moderate",true,false,false,false,null,["Brazil"],"Stromanthe Triostar has pink, cream, and green variegation with pink leaf undersides."],
  ["alocasia","Alocasia (Elephant Ear)","Alocasia amazonica","Araceae","Houseplant","Perennial","Average",PS,"Moderate","Moderate",true,false,false,true,"Summer",WW,"Alocasia has dramatic arrow-shaped leaves with bold silver veining on dark green."],
  ["philodendron-pink","Pink Princess Philodendron","Philodendron erubescens Pink","Araceae","Houseplant","Perennial","Average",PS,"Moderate","Moderate",true,false,false,false,null,["South America"],"Pink Princess has dark leaves splashed with bubblegum pink variegation — a collector's favorite."],
  ["anthurium-2","Anthurium Crystal","Anthurium crystallinum","Araceae","Houseplant","Perennial","Average",SH,"Moderate","Low",true,false,false,true,"All Year",["South America"],"Anthurium Crystal has velvety dark green leaves with dramatic silver veining."],
  ["monstera-adansonii","Swiss Cheese Vine","Monstera adansonii","Araceae","Vine","Perennial","Average",PS,"Easy","High",true,false,false,false,null,["South America"],"Swiss cheese vine has smaller leaves with more holes than Monstera deliciosa."],
  ["selaginella-2","Rainbow Fern","Selaginella uncinata","Selaginellaceae","Fern","Perennial","Frequent",SH,"Moderate","Moderate",true,false,false,false,null,["China"],"Rainbow fern has iridescent blue-green foliage that shimmers in different light angles."],
  ["passion-vine-2","Giant Granadilla","Passiflora quadrangularis","Passifloraceae","Vine","Perennial","Average",FS,"Moderate","High",false,true,true,true,"Summer",["South America"],"Giant granadilla has the largest passion fruit — up to 12 inches long with sweet pulp."],

  // ═══════ AUSTRALIAN NATIVE (15) ═══════
  ["eucalyptus","Eucalyptus","Eucalyptus globulus","Myrtaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Summer",["Australia","Nilgiris"],"Eucalyptus oil from Nilgiri hills is used worldwide for colds; koalas eat only eucalyptus leaves."],
  ["banksia","Banksia","Banksia serrata","Proteaceae","Shrub","Perennial","Minimum",FS,"Moderate","Low",false,false,false,true,"Autumn",["Australia"],"Banksia produces dramatic bottlebrush-like flower spikes that persist as woody cones."],
  ["grevillea","Grevillea (Spider Flower)","Grevillea robusta","Proteaceae","Tree","Perennial","Minimum",FS,"Easy","High",false,false,false,true,"Spring",["Australia","India"],"Grevillea produces spider-like orange flower clusters and is widely planted as a shade tree in India."],
  ["callistemon","Bottlebrush (Crimson)","Callistemon viminalis","Myrtaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Spring",["Australia","India"],"Weeping bottlebrush has crimson flower spikes on graceful drooping branches."],
  ["wattle","Golden Wattle","Acacia pycnantha","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Spring",["Australia"],"Golden wattle is Australia's national flower with fluffy golden pom-pom blooms."],
  ["melaleuca","Tea Tree","Melaleuca alternifolia","Myrtaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Summer",["Australia"],"Tea tree oil is a powerful antiseptic used for acne, cuts, and fungal infections."],
  ["leptospermum","Manuka","Leptospermum scoparium","Myrtaceae","Shrub","Perennial","Average",FS,"Moderate","Moderate",false,true,false,true,"Spring",["New Zealand"],"Manuka honey from these flowers is one of the world's most expensive honey varieties."],
  ["boronia","Boronia","Boronia megastigma","Rutaceae","Shrub","Perennial","Average",PS,"Moderate","Low",false,false,false,true,"Spring",["Australia"],"Boronia produces intensely fragrant brown and yellow bell flowers used in premium perfumery."],
  ["correa","Australian Fuchsia","Correa pulchella","Rutaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Winter",["Australia"],"Australian fuchsia produces tubular bell flowers in pink, red, and green through winter."],
  ["flannel-flower","Flannel Flower","Actinotus helianthi","Apiaceae","Flower","Perennial","Minimum",FS,"Moderate","Low",false,false,false,true,"Spring",["Australia"],"Flannel flower has soft, felt-textured white star-shaped flowers with green tips."],

  // ═══════ CHINESE / EAST ASIAN (15) ═══════
  ["lotus-sacred","Sacred Lotus","Nelumbo nucifera","Nelumbonaceae","Aquatic","Perennial","Frequent",FS,"Moderate","Moderate",false,true,true,true,"Summer",AI,"Sacred lotus rises from muddy water to bloom in perfection — symbol of purity across Asia."],
  ["chrysanthemum-2","Spider Chrysanthemum","Chrysanthemum morifolium","Asteraceae","Flower","Perennial","Average",FSPS,"Easy","Moderate",false,true,true,true,"Autumn",["China","Japan"],"Spider chrysanthemums have long, curling petals — one of the Four Gentlemen of Chinese art."],
  ["wintersweet","Wintersweet","Chimonanthus praecox","Calycanthaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"Winter",["China"],"Wintersweet produces intensely fragrant waxy yellow flowers on bare branches in midwinter."],
  ["plum-blossom","Plum Blossom (Mei)","Prunus mume","Rosaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Winter",["China","Japan"],"Plum blossom blooms in winter snow; China's national flower symbolizing resilience and hope."],
  ["peony-tree","Tree Peony","Paeonia suffruticosa","Paeoniaceae","Shrub","Perennial","Average",FSPS,"Moderate","Low",false,true,false,true,"Spring",["China"],"Tree peonies produce dinner-plate-sized blooms and can live for 100 years."],
  ["osmanthus-2","Fragrant Olive","Osmanthus fragrans","Oleaceae","Tree","Perennial","Average",FSPS,"Easy","Low",false,true,true,true,"Autumn",["China"],"Osmanthus perfumes autumn air throughout China; tiny flowers flavor tea, wine, and desserts."],
  ["chinese-pistache","Chinese Pistache","Pistacia chinensis","Anacardiaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,false,null,["China"],"Chinese pistache has the most spectacular autumn color of any shade tree."],
  ["dawn-redwood","Dawn Redwood","Metasequoia glyptostroboides","Cupressaceae","Tree","Perennial","Average",FSPS,"Easy","High",false,false,false,false,null,["China"],"Dawn redwood was thought extinct for millions of years until living trees were found in China in 1944."],
  ["paper-bush","Paper Bush (Edgeworthia)","Edgeworthia chrysantha","Thymelaeaceae","Shrub","Perennial","Average",PS,"Moderate","Moderate",false,false,false,true,"Winter",["China","Japan"],"Paper bush produces golden pendant flower clusters with an amazing honey-like fragrance in winter."],
  ["chinese-lantern","Chinese Lantern","Physalis alkekengi","Solanaceae","Flower","Perennial","Average",FSPS,"Easy","High",false,true,true,true,"Summer",["China"],"Chinese lantern has papery orange husks that glow like lanterns, used in dried arrangements."],

  // ═══════ MEDITERRANEAN (15) ═══════
  ["bougainvillea-white","White Bougainvillea","Bougainvillea spectabilis alba","Nyctaginaceae","Vine","Perennial","Minimum",FS,"Easy","High",false,false,false,true,"All Year",WW,"White bougainvillea creates cascading waterfalls of pristine white papery bracts."],
  ["oleander-pink","Pink Oleander","Nerium oleander roseum","Apocynaceae","Shrub","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Summer",WW,"Pink oleander lines Mediterranean highways and Indian railway tracks with effortless beauty."],
  ["myrtle","Myrtle","Myrtus communis","Myrtaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,true,true,"Summer",["Mediterranean"],"Myrtle was sacred to Aphrodite; its fragrant leaves and berries are used in Mediterranean cooking."],
  ["cistus","Rock Rose (Cistus)","Cistus × purpureus","Cistaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring",["Mediterranean"],"Rock roses produce crinkled tissue-paper flowers that last just one day but bloom prolifically."],
  ["santolina","Santolina (Cotton Lavender)","Santolina chamaecyparissus","Asteraceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Summer",["Mediterranean"],"Santolina has silvery aromatic foliage and button-like yellow flowers; deer hate it."],
  ["agapanthus-white","White Agapanthus","Agapanthus praecox albus","Amaryllidaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"White agapanthus produces elegant spherical clusters of trumpet-shaped pure white flowers."],
  ["lavandula","Spanish Lavender","Lavandula dentata","Lamiaceae","Flower","Perennial","Minimum",FS,"Easy","Moderate",false,true,true,true,"Spring-Autumn",["Mediterranean"],"Spanish lavender has toothed leaves and flower heads topped with purple rabbit-ear bracts."],
  ["teucrium","Germander","Teucrium chamaedrys","Lamiaceae","Shrub","Perennial","Minimum",FS,"Easy","Low",false,true,false,true,"Summer",["Mediterranean"],"Germander forms neat miniature hedges with pink flowers, used in knot gardens since Tudor times."],
  ["rosemary-prostrate","Trailing Rosemary","Rosmarinus officinalis Prostratus","Lamiaceae","Herb","Perennial","Minimum",FS,"Easy","Moderate",false,true,true,true,"Spring",["Mediterranean"],"Trailing rosemary cascades over walls and banks with fragrant blue flowers and aromatic needles."],
  ["convolvulus","Shrubby Bindweed","Convolvulus cneorum","Convolvulaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Summer",["Mediterranean"],"This silver-leafed shrub produces white trumpet flowers with pink buds — elegant and drought-tough."],

  // ═══════ CARNIVOROUS (5) ═══════
  ["cobra-plant","Cobra Lily","Darlingtonia californica","Sarraceniaceae","Carnivorous","Perennial","Frequent",PS,"Difficult","Low",false,false,false,true,"Spring",["California","Oregon"],"Cobra lily has a hooded pitcher that lures insects with false exit windows of light."],
  ["trumpet-pitcher","Trumpet Pitcher","Sarracenia","Sarraceniaceae","Carnivorous","Perennial","Frequent",FS,"Moderate","Moderate",false,false,false,true,"Spring",["Eastern USA"],"Trumpet pitchers produce dramatic veined tubes that trap and digest insects."],
  ["butterwort","Butterwort","Pinguicula","Lentibulariaceae","Carnivorous","Perennial","Average",PS,"Moderate","Low",true,false,false,true,"Spring",WW,"Butterworts have greasy leaves that trap tiny insects; they produce cute violet-like flowers."],
  ["bladderwort","Bladderwort","Utricularia","Lentibulariaceae","Carnivorous","Perennial","Frequent",FS,"Moderate","Moderate",false,false,false,true,"Summer",WW,"Bladderwort has the fastest trap in the plant kingdom — snapping shut in 1 millisecond underwater."],
  ["waterwheel","Waterwheel Plant","Aldrovanda vesiculosa","Droseraceae","Carnivorous","Perennial","Frequent",FS,"Difficult","Moderate",false,false,false,true,"Summer",WW,"Waterwheel is the aquatic Venus flytrap — a rootless floating plant that snaps shut on prey."],

  // ═══════ INDIAN REGIONAL SPECIALTIES (25) ═══════
  ["rhododendron-nilgiri","Nilgiri Rhododendron","Rhododendron nilagiricum","Ericaceae","Tree","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Spring",["Nilgiris"],"Endemic to Tamil Nadu's Nilgiri hills, this rare red rhododendron blooms at 2000m elevation."],
  ["neelakurinji","Neelakurinji","Strobilanthes kunthiana","Acanthaceae","Shrub","Perennial","Average",PS,"Moderate","Low",false,false,false,true,"Rare",["Western Ghats"],"Neelakurinji blooms once every 12 years, painting entire hillsides blue-purple in Kerala and Tamil Nadu."],
  ["karvi","Karvi (Topli Karvi)","Strobilanthes callosa","Acanthaceae","Shrub","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Rare",["Western Ghats"],"Karvi blooms once every 8 years in Maharashtra's Western Ghats, carpeting hills in purple."],
  ["brahmi-2","Brahmi (Water Hyssop)","Bacopa monnieri","Plantaginaceae","Herb","Perennial","Frequent",PS,"Easy","Moderate",false,true,false,true,"Summer",AI,"Brahmi is Ayurveda's top brain herb; it grows near water and enhances memory and focus."],
  ["peepal-2","Sacred Fig (Peepal)","Ficus religiosa","Moraceae","Tree","Perennial","Average",FSPS,"Easy","High",false,true,false,true,"Spring",AI,"Peepal is the only tree that produces oxygen 24 hours; worshipped on Saturdays in Hinduism."],
  ["shami","Shami Tree","Prosopis cineraria","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,true,true,true,"Spring",["Rajasthan"],"Shami is Rajasthan's state tree; its pods make sangri, a prized desert delicacy."],
  ["mahua","Mahua","Madhuca longifolia","Sapotaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",["Central India"],"Mahua flowers are naturally fermented into country liquor; seeds yield cooking oil used by tribal communities."],
  ["tendu","Tendu","Diospyros melanoxylon","Ebenaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"Spring",["Central India"],"Tendu leaves are used to roll bidi cigarettes — a multi-billion dollar forest product industry."],
  ["khejri","Khejri","Prosopis cineraria","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,true,true,true,"Spring",["Rajasthan"],"Khejri is the tree of the Thar Desert; 363 Bishnois sacrificed their lives protecting Khejri trees in 1730."],
  ["palas","Palas (Dhak)","Butea monosperma","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring",AI,"Palas flowers are the source of traditional Holi colors; the tree is called 'Flame of the Forest'."],
  ["arjun-2","Arjuna Tree","Terminalia arjuna","Combretaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"Arjuna bark strengthens the heart — one of Ayurveda's most important cardiovascular medicines."],
  ["rudraksha","Rudraksha","Elaeocarpus ganitrus","Elaeocarpaceae","Tree","Perennial","Average",PS,"Moderate","Low",false,true,false,true,"Spring",["Nepal","Java"],"Rudraksha seeds are sacred prayer beads in Hinduism; Lord Shiva is always depicted wearing them."],
  ["cinnamon-2","True Cinnamon","Cinnamomum verum","Lauraceae","Tree","Perennial","Average",PS,"Moderate","Moderate",false,true,true,true,"All Year",["Kerala","Sri Lanka"],"True cinnamon (dalchini) from Kerala's bark is milder and finer than Chinese cassia."],
  ["jack-tree-2","Wild Jackfruit","Artocarpus hirsutus","Moraceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,false,true,false,null,["Western Ghats"],"Wild jackfruit (Anjili) is endemic to the Western Ghats; its timber is prized in Kerala."],
  ["mango-2","Alphonso Mango","Mangifera indica Alphonso","Anacardiaceae","Tree","Perennial","Average",FS,"Moderate","Moderate",false,true,true,true,"Spring",["Ratnagiri","Devgad"],"Alphonso (Hapus) from Ratnagiri is the king of mangoes — saffron-colored, fibreless, and unmatched."],
  ["kokum-2","Kokum","Garcinia indica","Clusiaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",["Konkan"],"Kokum's dried rind souring agent and refreshing purple sherbet are treasures of Konkan cuisine."],
  ["sapota","Sapota (Chikoo)","Manilkara zapota","Sapotaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,true,true,"All Year",["Gujarat","Karnataka"],"Chikoo is one of India's sweetest fruits; the tree also produces chicle, the original chewing gum base."],
  ["sitaphal-2","Sugar Apple (Sitaphal)","Annona squamosa","Annonaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Autumn",AI,"Sitaphal has creamy custard-like white flesh segmented around black seeds — autumn's favorite fruit."],
  ["curry-patta","Sweet Neem (Curry Patta)","Murraya koenigii","Rutaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,true,true,"Spring",AI,"Every South Indian tempering (tadka) starts with curry leaves crackling in hot oil."],
  ["champak-2","Champak (Joy Perfume Tree)","Magnolia champaca","Magnoliaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"All Year",AI,"Champak's golden flowers are the secret base note of Joy perfume — once the world's costliest."],

  // ═══════ TEXTILE & FIBER (10) ═══════
  ["ramie","Ramie","Boehmeria nivea","Urticaceae","Crop","Perennial","Average",FS,"Easy","High",false,false,false,false,null,["Northeast India","China"],"Ramie fiber is 8x stronger than cotton and has been used in Chinese textiles for 6000 years."],
  ["kenaf","Kenaf","Hibiscus cannabinus","Malvaceae","Crop","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",AI,"Kenaf is a fast-growing hibiscus relative that produces fiber for paper and biodegradable composites."],
  ["kapok","Kapok Tree","Ceiba pentandra","Malvaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"Kapok tree produces silky fiber used to fill pillows and life jackets; it can float in water."],
  ["banana-fiber","Banana (Fiber)","Musa textilis","Musaceae","Crop","Perennial","Average",FSPS,"Easy","High",false,false,true,false,null,["Philippines","India"],"Manila hemp from banana stems produces one of the strongest natural fibers — used in marine rope."],
  ["agave-fiber","Century Plant","Agave americana","Asparagaceae","Succulent","Perennial","Minimum",FS,"Easy","Low",false,true,false,true,"Rare",WW,"Century plant blooms once after 10-30 years with a 25-foot flower spike, then dies."],

  // ═══════ DYE PLANTS (10) ═══════
  ["woad","Woad","Isatis tinctoria","Brassicaceae","Crop","Biennial","Average",FS,"Easy","High",false,true,false,true,"Spring",["Europe"],"Woad produced the blue dye that Celts used to paint their bodies before battle."],
  ["madder","Madder","Rubia tinctorum","Rubiaceae","Vine","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"Summer",WW,"Madder root produces Turkey Red dye — the most permanent natural red for textiles."],
  ["weld","Weld (Dyer's Rocket)","Reseda luteola","Resedaceae","Crop","Biennial","Average",FS,"Easy","High",false,false,false,true,"Summer",["Europe"],"Weld produces the brightest and most lightfast natural yellow dye for textiles."],
  ["annatto","Annatto","Bixa orellana","Bixaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"Annatto seeds produce the orange/red color in cheddar cheese, butter, and cosmetics."],
  ["pomegranate-dye","Dyer's Pomegranate","Punica granatum","Lythraceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"Pomegranate rinds produce yellow-gold dye used in Indian textiles for centuries."],

  // ═══════ PALMS (15) ═══════
  ["areca-palm","Areca Palm","Dypsis lutescens","Arecaceae","Palm","Perennial","Average",PS,"Easy","Moderate",true,false,false,true,"Summer",WW,"Areca palm is the most popular indoor palm, adding a tropical feel with golden-yellow cane stems."],
  ["fan-palm","Chinese Fan Palm","Livistona chinensis","Arecaceae","Palm","Perennial","Average",FSPS,"Easy","Moderate",true,false,false,false,null,WW,"Chinese fan palm has elegant circular fan-shaped fronds that droop gracefully at the tips."],
  ["majesty-palm","Majesty Palm","Ravenea rivularis","Arecaceae","Palm","Perennial","Frequent",PS,"Moderate","Moderate",true,false,false,false,null,["Madagascar"],"Majesty palm has symmetrical arching fronds; requires high humidity indoors."],
  ["palmetto","Saw Palmetto","Serenoa repens","Arecaceae","Palm","Perennial","Minimum",FS,"Easy","Low",false,true,true,false,null,["Southeast USA"],"Saw palmetto berry extract is one of the most popular supplements for prostate health."],
  ["traveler-palm","Traveler's Palm","Ravenala madagascariensis","Strelitziaceae","Palm","Perennial","Average",FS,"Easy","High",false,false,false,false,null,["Madagascar"],"Traveler's palm stores water in its leaf bases; thirsty travelers could drink from it."],
  ["bismarck-palm","Bismarck Palm","Bismarckia nobilis","Arecaceae","Palm","Perennial","Minimum",FS,"Easy","Low",false,false,false,false,null,["Madagascar"],"Bismarck palm has stunning silver-blue fan-shaped leaves up to 10 feet across."],
  ["bottle-palm","Bottle Palm","Hyophorbe lagenicaulis","Arecaceae","Palm","Perennial","Average",FS,"Easy","Low",false,false,false,false,null,["Mauritius"],"Bottle palm has a swollen bottle-shaped trunk; fewer than 500 remain in the wild."],
  ["foxtail-palm","Foxtail Palm","Wodyetia bifurcata","Arecaceae","Palm","Perennial","Average",FS,"Easy","Moderate",false,false,false,false,null,["Australia"],"Foxtail palm has plume-like fronds resembling a fox's bushy tail."],
  ["kentia-palm","Kentia Palm","Howea forsteriana","Arecaceae","Palm","Perennial","Average",SH,"Easy","Low",true,false,false,false,null,["Lord Howe Island"],"Kentia palm is the most elegant indoor palm, thriving in low light for decades."],
  ["pygmy-date","Pygmy Date Palm","Phoenix roebelenii","Arecaceae","Palm","Perennial","Average",FSPS,"Easy","Low",true,false,false,false,null,WW,"Pygmy date palm grows only 6-10 feet tall with soft, feathery fronds."],

  // ═══════ PERENNIAL FLOWERS (20) ═══════
  ["peony","Peony","Paeonia lactiflora","Paeoniaceae","Flower","Perennial","Average",FS,"Moderate","Low",false,true,false,true,"Spring",WW,"Peonies produce lush, fragrant blooms and can live for 100 years; ants help open the buds."],
  ["iris-bearded","Bearded Iris","Iris germanica","Iridaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Bearded iris has fuzzy 'beards' on the falls; comes in every color including black."],
  ["delphinium","Delphinium","Delphinium elatum","Ranunculaceae","Flower","Perennial","Average",FS,"Moderate","Moderate",false,true,false,true,"Summer",WW,"Delphinium produces 6-foot spires of true blue flowers that define cottage gardens."],
  ["phlox","Garden Phlox","Phlox paniculata","Polemoniaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Phlox produces fragrant dome-shaped flower clusters in every color from white to deep purple."],
  ["hollyhock","Hollyhock","Alcea rosea","Malvaceae","Flower","Biennial","Average",FS,"Easy","High",false,true,false,true,"Summer",WW,"Hollyhocks send up 8-foot spires of saucer-shaped flowers along traditional cottage garden walls."],
  ["bleeding-heart","Bleeding Heart","Lamprocapnos spectabilis","Papaveraceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,true,false,true,"Spring",WW,"Bleeding heart has arching stems of perfect heart-shaped pink and white locket flowers."],
  ["anemone-2","Poppy Anemone","Anemone coronaria","Ranunculaceae","Flower","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Poppy anemones produce vivid red, purple, and white flowers with dark centers."],
  ["dianthus-2","Dianthus (Pinks)","Dianthus plumarius","Caryophyllaceae","Flower","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Spring-Summer",WW,"Pinks have fringed petals with a spicy clove fragrance; growing since the Roman era."],
  ["sedum-stonecrop","Stonecrop Sedum","Sedum spectabile","Crassulaceae","Flower","Perennial","Minimum",FS,"Easy","Low",false,false,false,true,"Autumn",WW,"Stonecrop sedum produces flat flower heads that turn from pink to russet; butterflies love them."],
  ["coreopsis","Coreopsis (Tickseed)","Coreopsis grandiflora","Asteraceae","Flower","Perennial","Minimum",FS,"Easy","High",false,false,false,true,"Summer",WW,"Coreopsis produces cheerful yellow daisy-like flowers non-stop all summer with zero fuss."],
  ["catmint","Catmint","Nepeta × faassenii","Lamiaceae","Flower","Perennial","Minimum",FS,"Easy","Moderate",false,true,false,true,"Summer",WW,"Catmint produces lavender-blue flower spikes and aromatic grey-green foliage; cats love it."],
  ["crocosmia","Crocosmia (Montbretia)","Crocosmia × crocosmiiflora","Iridaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Crocosmia produces arching sprays of fiery orange-red tubular flowers on sword-like leaves."],
  ["kniphofia","Red Hot Poker","Kniphofia uvaria","Asphodelaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Red hot poker produces dramatic torch-like flower spikes in red, orange, and yellow."],
  ["rudbeckia","Gloriosa Daisy","Rudbeckia fulgida","Asteraceae","Flower","Perennial","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Gloriosa daisy produces golden flowers with mahogany zones around dark chocolate centers."],
  ["salvia-red","Scarlet Sage","Salvia splendens","Lamiaceae","Flower","Annual","Average",FS,"Easy","High",false,false,false,true,"Summer",WW,"Scarlet sage produces brilliant red flower spikes that hummingbirds adore."],

  // ═══════ COMPANION PLANTS (15) ═══════
  ["nasturtium","Nasturtium","Tropaeolum majus","Tropaeolaceae","Flower","Annual","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Nasturtium flowers and leaves are edible with a peppery watercress flavor; traps aphids away from crops."],
  ["marigold-pot","Pot Marigold (Calendula)","Calendula officinalis","Asteraceae","Flower","Annual","Average",FS,"Easy","High",false,true,true,true,"Spring-Autumn",WW,"Calendula petals are edible and medicinal; used in salves for skin healing since ancient Egypt."],
  ["tansy","Tansy","Tanacetum vulgare","Asteraceae","Herb","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Summer",WW,"Tansy repels ants, flies, and mosquitoes; its button-like yellow flowers were used in funeral wreaths."],
  ["feverfew","Feverfew","Tanacetum parthenium","Asteraceae","Herb","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"Summer",WW,"Feverfew is one of the most effective herbal remedies for migraine prevention."],
  ["comfrey","Comfrey","Symphytum officinale","Boraginaceae","Herb","Perennial","Average",FSPS,"Easy","High",false,true,false,true,"Summer",WW,"Comfrey is called 'knitbone' for its ability to speed bone and tissue healing; superb compost activator."],
  ["pyrethrum","Pyrethrum","Tanacetum cinerariifolium","Asteraceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Summer",WW,"Pyrethrum daisy produces the world's safest natural insecticide — pyrethrin — from its dried flowers."],
  ["sweet-potato","Sweet Potato","Ipomoea batatas","Convolvulaceae","Vegetable","Perennial","Average",FS,"Easy","High",false,true,true,true,"Summer",AI,"Sweet potato is one of the most nutritious root vegetables; orange varieties are richest in beta-carotene."],
  ["okra","Okra (Bhindi)","Abelmoschus esculentus","Malvaceae","Vegetable","Annual","Average",FS,"Easy","High",false,true,true,true,"Summer",AI,"Bhindi is one of India's most loved vegetables; its mucilage thickens soups and stews naturally."],
  ["pumpkin","Pumpkin","Cucurbita maxima","Cucurbitaceae","Vegetable","Annual","Average",FS,"Easy","High",false,true,true,true,"Summer",WW,"Pumpkins can grow over 2000 pounds; seeds are rich in zinc and magnesium."],
  ["watermelon","Watermelon","Citrullus lanatus","Cucurbitaceae","Fruit","Annual","Average",FS,"Easy","High",false,false,true,true,"Summer",AI,"Watermelon is 92% water; in India, it's the quintessential summer fruit sold from roadside carts."],

  // ═══════ WORLD TREES (20) ═══════
  ["baobab","Baobab","Adansonia digitata","Malvaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,true,true,true,"Summer",["Africa"],"Baobab trees can live 3000 years and store 32000 gallons of water in their massive trunks."],
  ["moreton-bay","Moreton Bay Fig","Ficus macrophylla","Moraceae","Tree","Perennial","Average",FS,"Easy","High",false,false,false,false,null,["Australia"],"Moreton Bay fig develops massive buttress roots and can spread over an entire city block."],
  ["cedar-of-lebanon","Cedar of Lebanon","Cedrus libani","Pinaceae","Tree","Perennial","Average",FS,"Moderate","Low",false,true,false,false,null,["Lebanon"],"Cedar of Lebanon appears 75 times in the Bible; its wood built King Solomon's temple."],
  ["boab","Australian Boab","Adansonia gregorii","Malvaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,true,true,false,null,["Australia"],"The Prison Boab in Derby is 1500 years old with a hollow trunk used as a temporary lockup."],
  ["rainbow-eucalyptus","Rainbow Eucalyptus","Eucalyptus deglupta","Myrtaceae","Tree","Perennial","Frequent",FS,"Easy","High",false,false,false,false,null,["Philippines"],"Rainbow eucalyptus peels bark to reveal stunning streaks of green, blue, orange, and maroon."],
  ["dragon-tree","Dragon Tree","Dracaena draco","Asparagaceae","Tree","Perennial","Minimum",FS,"Easy","Low",false,true,false,false,null,["Canary Islands"],"Dragon tree grows for centuries into an umbrella shape; its red resin was used as dragon's blood."],
  ["jacaranda","Jacaranda","Jacaranda mimosifolia","Bignoniaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Jacaranda transforms city streets into purple tunnels when it blooms; iconic in Bangalore."],
  ["copper-beech","Copper Beech","Fagus sylvatica purpurea","Fagaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,false,true,false,null,WW,"Copper beech has dramatic deep purple leaves that contrast beautifully with green landscapes."],
  ["birch-silver","Silver Birch","Betula pendula","Betulaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,false,null,WW,"Silver birch has striking white bark that peels in papery strips; Russia's national tree."],
  ["weeping-willow","Weeping Willow","Salix babylonica","Salicaceae","Tree","Perennial","Frequent",FS,"Easy","High",false,true,false,true,"Spring",WW,"Weeping willow's cascading branches touch the water's edge; aspirin was first derived from willow bark."],
  ["english-oak","English Oak","Quercus robur","Fagaceae","Tree","Perennial","Average",FS,"Easy","Low",false,true,true,true,"Spring",WW,"English oak can live 1000 years; its acorns fed medieval Europe and its timber built the British navy."],
  ["bonsai-olive","Olive Bonsai","Olea europaea bonsai","Oleaceae","Tree","Perennial","Minimum",FS,"Easy","Low",true,false,false,false,null,WW,"Olive bonsai develops a gnarled, ancient-looking trunk even when young; drought-tolerant."],
  ["flame-tree","Flame Tree (Illawarra)","Brachychiton acerifolius","Malvaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",["Australia"],"Flame tree drops all its leaves then covers itself in brilliant scarlet bell-shaped flowers."],
  ["kapok-2","White Silk Cotton","Ceiba pentandra","Malvaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",AI,"The massive buttress roots of the kapok tree were used as canoe hulls by indigenous peoples."],
  ["paulownia","Paulownia (Empress Tree)","Paulownia tomentosa","Paulowniaceae","Tree","Perennial","Average",FS,"Easy","High",false,true,false,true,"Spring",WW,"Paulownia is the fastest-growing hardwood tree — growing 15 feet per year; its timber is prized in Japan."],
  ["tulip-tree","Tulip Tree","Liriodendron tulipifera","Magnoliaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Tulip tree produces tulip-shaped flowers high in its canopy; the tallest eastern North American hardwood."],
  ["sycamore","London Plane (Sycamore)","Platanus × acerifolia","Platanaceae","Tree","Perennial","Average",FS,"Easy","High",false,false,false,false,null,WW,"London plane survives urban pollution better than any tree; its bark peels in jigsaw-puzzle patterns."],
  ["catalpa-2","Indian Bean Tree","Catalpa bignonioides","Bignoniaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Indian bean tree produces showy orchid-like white flowers and long dangling bean pods."],
  ["liquidambar","Sweet Gum","Liquidambar styraciflua","Altingiaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,false,null,WW,"Sweet gum has star-shaped leaves that turn spectacular purple, red, orange, and gold in autumn."],
  ["zelkova","Japanese Zelkova","Zelkova serrata","Ulmaceae","Tree","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,false,null,["Japan"],"Japanese zelkova is replacing the American elm as a street tree; it resists Dutch elm disease."],

  // ═══════ SPRING BULBS & PERENNIALS (15) ═══════
  ["ranunculus","Ranunculus","Ranunculus asiaticus","Ranunculaceae","Flower","Perennial","Average",FS,"Moderate","Moderate",false,false,false,true,"Spring",WW,"Ranunculus produces dozens of paper-thin petals layered like a rose in vivid colors."],
  ["fritillaria","Fritillary (Crown Imperial)","Fritillaria imperialis","Liliaceae","Flower","Perennial","Average",FS,"Moderate","Low",false,false,false,true,"Spring",WW,"Crown imperial produces a ring of bell-shaped orange flowers topped by a pineapple-like crown of leaves."],
  ["scilla","Scilla (Siberian Squill)","Scilla siberica","Asparagaceae","Flower","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Scilla covers woodland floors in a carpet of electric blue bell flowers in early spring."],
  ["allium-orn","Ornamental Allium","Allium giganteum","Amaryllidaceae","Flower","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Giant allium produces dramatic purple spheres up to 6 inches across on 4-foot stems."],
  ["eranthis","Winter Aconite","Eranthis hyemalis","Ranunculaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,true,false,true,"Winter",["Europe"],"Winter aconite is one of the first flowers of the year, pushing through snow with golden cups."],
  ["arum-italicum","Italian Arum","Arum italicum","Araceae","Flower","Perennial","Average",SH,"Easy","Moderate",false,true,false,true,"Spring",WW,"Italian arum has arrow-shaped leaves with white veining and bright orange-red berries in autumn."],
  ["leucojum","Summer Snowflake","Leucojum aestivum","Amaryllidaceae","Flower","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Summer snowflake has nodding white bell flowers with green spots; taller than its cousin snowdrop."],
  ["chionodoxa","Glory of the Snow","Chionodoxa luciliae","Asparagaceae","Flower","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Glory of the Snow blooms as snow melts with star-shaped blue flowers with white centers."],

  // ═══════ VEGETABLES & FOOD (12) ═══════
  ["eggplant","Eggplant (Brinjal)","Solanum melongena","Solanaceae","Vegetable","Annual","Average",FS,"Easy","Moderate",false,true,true,true,"Summer",AI,"India is the world's second-largest eggplant producer; the purple baingan bharta is iconic."],
  ["cauliflower","Cauliflower (Gobi)","Brassica oleracea var. botrytis","Brassicaceae","Vegetable","Annual","Average",FS,"Easy","Moderate",false,true,true,true,"Winter",AI,"Gobi is essential in North Indian cuisine — aloo gobi and gobi paratha are national favorites."],
  ["cabbage","Cabbage (Patta Gobi)","Brassica oleracea var. capitata","Brassicaceae","Vegetable","Annual","Average",FSPS,"Easy","Moderate",false,true,true,false,null,WW,"Cabbage can be fermented into sauerkraut and kimchi, some of the world's oldest preserved foods."],
  ["broccoli","Broccoli","Brassica oleracea var. italica","Brassicaceae","Vegetable","Annual","Average",FSPS,"Easy","Moderate",false,true,true,true,"Spring",WW,"Broccoli florets are actually thousands of tiny flower buds; one of the most nutrient-dense vegetables."],
  ["radish","Radish (Mooli)","Raphanus sativus","Brassicaceae","Vegetable","Annual","Average",FSPS,"Easy","High",false,true,true,true,"Winter",AI,"Mooli paratha is North India's favorite winter breakfast; Indian radishes grow up to 2 feet long."],
  ["carrot","Carrot (Gajar)","Daucus carota","Apiaceae","Vegetable","Biennial","Average",FS,"Easy","Moderate",false,true,true,true,"Winter",AI,"The original carrots were purple; orange carrots were bred by the Dutch to honor William of Orange."],
  ["pea","Garden Pea (Matar)","Pisum sativum","Fabaceae","Vegetable","Annual","Average",FSPS,"Easy","Moderate",false,true,true,true,"Winter",AI,"Gregor Mendel discovered the laws of genetics by studying pea plants; matar paneer uses them daily."],
  ["cucumber","Cucumber (Kheera)","Cucumis sativus","Cucurbitaceae","Vegetable","Annual","Average",FS,"Easy","High",false,true,true,true,"Summer",AI,"Cucumbers are 96% water; they've been cultivated in India for 3000 years."],
  ["lettuce","Lettuce","Lactuca sativa","Asteraceae","Vegetable","Annual","Average",PS,"Easy","High",false,false,true,false,null,WW,"Lettuce has been cultivated for 5000 years; ancient Egyptians first grew it for its oily seeds."],
  ["beetroot","Beetroot (Chukandar)","Beta vulgaris","Amaranthaceae","Vegetable","Biennial","Average",FS,"Easy","Moderate",false,true,true,true,"Winter",AI,"Beetroot juice improves athletic endurance by 16%; its deep red color stains everything."],
  ["garlic","Garlic (Lehsun)","Allium sativum","Amaryllidaceae","Vegetable","Perennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",AI,"India is the world's second-largest garlic producer; raw garlic has powerful antimicrobial properties."],
  ["onion","Onion (Pyaaz)","Allium cepa","Amaryllidaceae","Vegetable","Biennial","Average",FS,"Easy","Moderate",false,true,true,true,"Spring",AI,"India is the world's second-largest onion producer; price spikes can topple governments."],

  // ═══════ ORNAMENTAL SHRUBS (10) ═══════
  ["abelia","Abelia","Abelia × grandiflora","Caprifoliaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Summer",WW,"Abelia produces clusters of tubular pink-white flowers from summer through frost; attracts butterflies."],
  ["ceanothus","California Lilac","Ceanothus","Rhamnaceae","Shrub","Perennial","Minimum",FS,"Easy","Moderate",false,false,false,true,"Spring",["California"],"California lilac produces dense clouds of electric blue flowers; fixes nitrogen in the soil."],
  ["kolkwitzia","Beauty Bush","Kolkwitzia amabilis","Caprifoliaceae","Shrub","Perennial","Average",FS,"Easy","Moderate",false,false,false,true,"Spring",["China"],"Beauty bush erupts in cascading pink bell-shaped flowers that completely cover the arching branches."],
  ["ninebarks","Ninebark","Physocarpus opulifolius","Rosaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",["North America"],"Ninebark has rich burgundy foliage with peeling bark in nine distinct layers, hence the name."],
  ["itea","Sweetspire","Itea virginica","Iteaceae","Shrub","Perennial","Average",PS,"Easy","Moderate",false,false,false,true,"Summer",["North America"],"Sweetspire produces fragrant white bottlebrush-like flower spikes and spectacular red autumn color."],

  // ═══════ FINAL ENTRIES (10) ═══════
  ["persian-silk","Persian Silk Tree","Albizia julibrissin","Fabaceae","Tree","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"Summer",WW,"Persian silk tree has fern-like leaves and fluffy pink powder-puff flowers that attract hummingbirds."],
  ["snowball-bush","Snowball Viburnum","Viburnum opulus Roseum","Adoxaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",WW,"Snowball viburnum produces perfectly round clusters of white flowers that turn pink with age."],
  ["winterberry","Winterberry Holly","Ilex verticillata","Aquifoliaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,false,false,true,"Spring",["North America"],"Winterberry drops its leaves to reveal branches covered in brilliant red berries all winter."],
  ["hamelia","Firebush","Hamelia patens","Rubiaceae","Shrub","Perennial","Average",FS,"Easy","High",false,true,false,true,"All Year",WW,"Firebush produces clusters of orange-red tubular flowers that are irresistible to hummingbirds."],
  ["tibouchina","Princess Flower","Tibouchina urvilleana","Melastomataceae","Shrub","Perennial","Average",FS,"Moderate","Moderate",false,false,false,true,"Summer",["Brazil"],"Princess flower produces spectacular 3-inch purple-violet flowers with contrasting stamens."],
  ["plumbago","Plumbago","Plumbago auriculata","Plumbaginaceae","Shrub","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"All Year",["South Africa"],"Plumbago produces phlox-like clusters of sky-blue flowers almost year-round in warm climates."],
  ["golden-shower","Golden Shower Tree","Cassia fistula","Fabaceae","Tree","Perennial","Average",FS,"Easy","Moderate",false,true,false,true,"Summer",AI,"Golden shower (Amaltas) drapes entire trees in cascading golden flower chains; Kerala's state flower."],
  ["ixora","Ixora (Jungle Geranium)","Ixora coccinea","Rubiaceae","Shrub","Perennial","Average",FSPS,"Easy","Moderate",false,true,false,true,"All Year",AI,"Ixora produces dense spherical clusters of tiny flowers in red, orange, yellow, and pink."],
  ["duranta","Duranta (Golden Dewdrop)","Duranta erecta","Verbenaceae","Shrub","Perennial","Average",FS,"Easy","High",false,true,false,true,"All Year",AI,"Duranta produces cascading chains of lilac flowers followed by golden berry clusters."],
  ["tecoma","Yellow Bells (Tecoma)","Tecoma stans","Bignoniaceae","Shrub","Perennial","Minimum",FS,"Easy","High",false,true,false,true,"All Year",AI,"Yellow bells produce bright trumpet-shaped flowers continuously; one of India's most popular hedge plants."],
];

export const EXTENDED_PLANTS_P6: LocalPlant[] = DATA.map(expand);
